import 'package:collectarr_app/core/api/dto/catalog/catalog_item_dto.dart';
import 'package:collectarr_app/core/models/owned_item.dart';
import 'package:collectarr_app/core/models/tracking_entry.dart';
import 'package:collectarr_app/core/models/tracking_source.dart';
import 'package:collectarr_app/core/models/tracking_status.dart';
import 'package:collectarr_app/dev/seeds/seed_helpers.dart';
import 'package:collectarr_app/test/helpers/test_data_factories.dart';

List<CatalogItem> bookSeedCatalogItems() => [
      testCatalogItem(
        id: 'seed-book-01',
        kind: 'book',
        title: 'Dune',
        synopsis:
            'A noble family becomes embroiled in a war for control of the most valuable substance in the universe.',
        publisher: 'Chilton Books',
        releaseYear: 1965,
        releaseDate: DateTime.utc(1965, 8, 1),
        editionTitle: 'Mass Market Paperback',
        physicalFormat: 'Paperback',
        physicalFormatLabel: 'Mass Market Paperback',
        barcode: '9780441172719',
        country: 'US',
        language: 'en',
        ageRating: 'Adult',
        sortKey: 'dune-0001',
        itemNumber: '1',
        series: const CatalogSeriesDetailsDto(
          seriesId: 'seed-series-dune',
          seriesTitle: 'Dune',
          volumeName: 'Dune Chronicles',
          volumeNumber: '1',
          volumeStartYear: 1965,
          tags: 'sci-fi, politics, ecology, space opera',
        ),
        publishing: const CatalogPublishingDetailsDto(
          pageCount: 412,
          coverPriceCents: 999,
          currency: 'USD',
          imprint: 'Ace',
        ),
        creators: [
          {'name': 'Frank Herbert', 'role': 'author'},
        ],
        characters: [
          'Paul Atreides',
          'Duke Leto Atreides',
          'Baron Harkonnen',
          'Lady Jessica',
        ],
        storyArcs: ['Arrakis Saga'],
        genres: ['sci-fi', 'politics', 'space opera'],
        editions: [
          CatalogEdition(
            id: 'seed-ed-dune-pb',
            title: 'Mass Market Paperback',
            format: 'Paperback',
            publisher: 'Ace Books',
            isbn: '9780441172719',
            releaseDate: DateTime.utc(1990, 9, 1),
            variants: [
              CatalogVariant(
                id: 'seed-var-dune-pb',
                name: 'Paperback',
                variantType: 'physical',
                isbn: '9780441172719',
                coverPriceCents: 999,
                currency: 'USD',
                isPrimary: true,
              ),
            ],
          ),
        ],
      ),
      testCatalogItem(
        id: 'seed-book-02',
        kind: 'book',
        title: 'Dune Messiah',
        synopsis:
            'Paul Atreides faces a conspiracy to overthrow him twelve years after becoming Emperor.',
        publisher: 'Chilton Books',
        releaseYear: 1969,
        releaseDate: DateTime.utc(1969, 10, 1),
        sortKey: 'dune-0002',
        itemNumber: '2',
        series: const CatalogSeriesDetailsDto(
          seriesId: 'seed-series-dune',
          seriesTitle: 'Dune',
          volumeNumber: '1',
        ),
        publishing: const CatalogPublishingDetailsDto(pageCount: 256),
        creators: [
          {'name': 'Frank Herbert', 'role': 'author'},
        ],
        characters: ['Paul Atreides', 'Alia Atreides', 'Chani'],
        storyArcs: ['Arrakis Saga'],
        genres: ['sci-fi', 'politics'],
      ),
      testCatalogItem(
        id: 'seed-book-03',
        kind: 'book',
        title: 'Foundation',
        synopsis:
            'A mathematician predicts the fall of the Galactic Empire and creates a plan to preserve knowledge.',
        publisher: 'Gnome Press',
        releaseYear: 1951,
        releaseDate: DateTime.utc(1951, 5, 1),
        sortKey: 'foundation-0001',
        publishing: const CatalogPublishingDetailsDto(
          pageCount: 244,
          coverPriceCents: 899,
          currency: 'USD',
          imprint: 'Spectra',
        ),
        creators: [
          {'name': 'Isaac Asimov', 'role': 'author'},
        ],
        characters: ['Hari Seldon', 'Salvor Hardin'],
        genres: ['sci-fi', 'galactic empire'],
      ),
      testCatalogItem(
        id: 'seed-book-04',
        kind: 'book',
        title: '1984',
        synopsis:
            'In a totalitarian future, a man rebels against the oppressive government that controls every aspect of life.',
        publisher: 'Secker & Warburg',
        releaseYear: 1949,
        releaseDate: DateTime.utc(1949, 6, 8),
        country: 'GB',
        language: 'en',
        sortKey: 'nineteen-eighty-four-0001',
        publishing: const CatalogPublishingDetailsDto(
          pageCount: 328,
          imprint: 'Penguin Classics',
        ),
        creators: [
          {'name': 'George Orwell', 'role': 'author'},
        ],
        characters: ['Winston Smith', 'Big Brother', 'Julia', 'O\'Brien'],
        genres: ['dystopia', 'political fiction', 'classic'],
      ),
      testCatalogItem(
        id: 'seed-book-05',
        kind: 'book',
        title: 'Neuromancer',
        synopsis:
            'A washed-up computer hacker is hired for one last job in a world of artificial intelligence.',
        publisher: 'Ace Books',
        releaseYear: 1984,
        releaseDate: DateTime.utc(1984, 7, 1),
        sortKey: 'sprawl-trilogy-0001',
        publishing: const CatalogPublishingDetailsDto(pageCount: 271),
        creators: [
          {'name': 'William Gibson', 'role': 'author'},
        ],
        characters: ['Case', 'Molly Millions', 'Wintermute'],
        genres: ['cyberpunk', 'sci-fi'],
      ),
      testCatalogItem(
        id: 'seed-book-06',
        kind: 'book',
        title: 'The Hitchhiker\'s Guide to the Galaxy',
        synopsis:
            'Seconds before Earth is destroyed, Arthur Dent is saved by his friend Ford Prefect.',
        publisher: 'Pan Books',
        releaseYear: 1979,
        releaseDate: DateTime.utc(1979, 10, 12),
        country: 'GB',
        sortKey: 'hitchhikers-guide-0001',
        publishing: const CatalogPublishingDetailsDto(pageCount: 180),
        creators: [
          {'name': 'Douglas Adams', 'role': 'author'},
        ],
        characters: [
          'Arthur Dent',
          'Ford Prefect',
          'Zaphod Beeblebrox',
          'Marvin',
        ],
        genres: ['sci-fi', 'comedy', 'satire'],
      ),
      testCatalogItem(
        id: 'seed-book-07',
        kind: 'book',
        title: 'The Fellowship of the Ring',
        synopsis:
            'A hobbit inherits a ring of power and begins a journey to destroy it.',
        publisher: 'George Allen & Unwin',
        releaseYear: 1954,
        releaseDate: DateTime.utc(1954, 7, 29),
        country: 'GB',
        sortKey: 'lord-of-the-rings-0001',
        itemNumber: '1',
        series: const CatalogSeriesDetailsDto(
          seriesId: 'seed-series-lotr',
          seriesTitle: 'The Lord of the Rings',
          volumeName: 'The Lord of the Rings',
          volumeNumber: '1',
          volumeStartYear: 1954,
          tags: 'fantasy, epic, quest',
        ),
        publishing: const CatalogPublishingDetailsDto(pageCount: 423),
        creators: [
          {'name': 'J.R.R. Tolkien', 'role': 'author'},
        ],
        characters: ['Frodo Baggins', 'Gandalf', 'Aragorn', 'Sauron'],
        storyArcs: ['War of the Ring'],
        genres: ['fantasy', 'epic'],
      ),
      testCatalogItem(
        id: 'seed-book-08',
        kind: 'book',
        title: 'The Two Towers',
        synopsis:
            'The fellowship is broken as war spreads and the quest to destroy the ring continues.',
        publisher: 'George Allen & Unwin',
        releaseYear: 1954,
        releaseDate: DateTime.utc(1954, 11, 11),
        country: 'GB',
        sortKey: 'lord-of-the-rings-0002',
        itemNumber: '2',
        series: const CatalogSeriesDetailsDto(
          seriesId: 'seed-series-lotr',
          seriesTitle: 'The Lord of the Rings',
          volumeNumber: '1',
        ),
        publishing: const CatalogPublishingDetailsDto(pageCount: 352),
        creators: [
          {'name': 'J.R.R. Tolkien', 'role': 'author'},
        ],
        characters: ['Frodo Baggins', 'Samwise Gamgee', 'Gollum'],
        storyArcs: ['War of the Ring'],
        genres: ['fantasy', 'epic', 'war'],
      ),
      testCatalogItem(
        id: 'seed-book-09',
        kind: 'book',
        title: 'The Return of the King',
        synopsis:
            'The final battle for Middle-earth begins while Frodo approaches Mount Doom.',
        publisher: 'George Allen & Unwin',
        releaseYear: 1955,
        releaseDate: DateTime.utc(1955, 10, 20),
        country: 'GB',
        sortKey: 'lord-of-the-rings-0003',
        itemNumber: '3',
        series: const CatalogSeriesDetailsDto(
          seriesId: 'seed-series-lotr',
          seriesTitle: 'The Lord of the Rings',
          volumeNumber: '1',
        ),
        publishing: const CatalogPublishingDetailsDto(pageCount: 416),
        creators: [
          {'name': 'J.R.R. Tolkien', 'role': 'author'},
        ],
        characters: ['Frodo Baggins', 'Aragorn', 'Sauron'],
        storyArcs: ['War of the Ring'],
        genres: ['fantasy', 'epic'],
      ),
      testCatalogItem(
        id: 'seed-book-10',
        kind: 'book',
        title: 'The Martian',
        synopsis:
            'An astronaut must rely on his ingenuity to survive alone on Mars after being presumed dead.',
        publisher: 'Crown Publishing',
        releaseYear: 2011,
        releaseDate: DateTime.utc(2011, 3, 1),
        sortKey: 'the-martian-0001',
        publishing: const CatalogPublishingDetailsDto(
          pageCount: 369,
          coverPriceCents: 2400,
          currency: 'USD',
        ),
        creators: [
          {'name': 'Andy Weir', 'role': 'author'},
        ],
        characters: ['Mark Watney', 'Melissa Lewis'],
        genres: ['sci-fi', 'survival', 'humor'],
        editions: [
          CatalogEdition(
            id: 'seed-ed-martian-hc',
            title: 'Hardcover',
            format: 'Hardcover',
            publisher: 'Crown',
            isbn: '9780804139021',
            releaseDate: DateTime.utc(2014, 2, 11),
            variants: [
              CatalogVariant(
                id: 'seed-var-martian-hc',
                name: 'Hardcover',
                variantType: 'physical',
                isbn: '9780804139021',
                coverPriceCents: 2400,
                currency: 'USD',
                isPrimary: true,
              ),
            ],
          ),
        ],
      ),
    ];

List<OwnedItem> bookSeedOwnedItems(DateTime now) => [
      OwnedItem(
        id: 'seed-owned-book-01',
        catalogRef: seedCatalogRef('seed-book-01'),
        createdAt: now.subtract(const Duration(days: 500)),
        updatedAt: now,
        isDigital: false,
        condition: 'Very Good',
        purchaseDate: DateTime.utc(2020, 3, 15),
        pricePaidCents: 999,
        currency: 'USD',
        personalNotes: 'Signed by the estate',
        quantity: 1,
        rating: 10,
        readStatus: 'completed',
        startedAt: DateTime.utc(2020, 4, 1),
        finishedAt: DateTime.utc(2020, 5, 10),
        details: const ComicOwnedDetails(signedBy: 'Estate of Frank Herbert'),
        purchaseStore: 'Powell\'s Books',
      ),
      OwnedItem(
        id: 'seed-owned-book-07',
        catalogRef: seedCatalogRef('seed-book-07'),
        createdAt: now.subtract(const Duration(days: 1000)),
        updatedAt: now,
        isDigital: false,
        condition: 'Good',
        pricePaidCents: 1500,
        currency: 'USD',
        rating: 10,
        readStatus: 'completed',
        tags: 'fantasy,classic,tolkien',
      ),
    ];

List<TrackingEntry> bookSeedTrackingEntries(DateTime now) => [
      TrackingEntry(
        id: 'seed-track-02',
        catalogRef: seedCatalogRef('seed-book-02'),
        sourceType: TrackingSourceType.physical,
        status: MediaTrackingStatus.inProgress,
        progressCurrent: 120,
        progressTotal: 256,
        startedAt: DateTime.utc(2025, 5, 1),
        updatedAt: now,
      ),
      TrackingEntry(
        id: 'seed-track-08',
        catalogRef: seedCatalogRef('seed-book-05'),
        sourceType: TrackingSourceType.physical,
        status: MediaTrackingStatus.dropped,
        progressCurrent: 80,
        progressTotal: 271,
        notes: 'Couldn\'t get into it',
        updatedAt: now,
      ),
    ];
