import 'package:collectarr_app/core/api/dto/catalog/catalog_item_dto.dart';
import 'package:collectarr_app/core/models/owned_item.dart';
import 'package:collectarr_app/core/models/tracking_entry.dart';
import 'package:collectarr_app/core/models/tracking_source.dart';
import 'package:collectarr_app/core/models/tracking_status.dart';
import 'package:collectarr_app/dev/seeds/seed_helpers.dart';
import 'package:collectarr_app/test/helpers/test_data_factories.dart';

List<CatalogItem> comicSeedCatalogItems() => [
      testCatalogItem(
        id: 'seed-comic-01',
        kind: 'comic',
        title: 'Saga',
        synopsis:
            'Two soldiers from opposite sides of a galactic war fall in love and become fugitives.',
        publisher: 'Image Comics',
        releaseYear: 2012,
        releaseDate: DateTime.utc(2012, 3, 14),
        editionTitle: 'Single Issue',
        physicalFormat: 'Single Issue',
        barcode: '70985302415600111',
        country: 'US',
        language: 'en',
        ageRating: 'Mature',
        sortKey: 'saga-0001',
        itemNumber: '1',
        series: const CatalogSeriesDetailsDto(
          seriesId: 'seed-series-saga',
          seriesTitle: 'Saga',
          volumeName: 'Saga',
          volumeNumber: '1',
          volumeStartYear: 2012,
          tags: 'sci-fi, fantasy, romance',
        ),
        publishing: const CatalogPublishingDetailsDto(
          pageCount: 44,
          coverPriceCents: 299,
          currency: 'USD',
          imprint: 'Image',
        ),
        creators: [
          {'name': 'Brian K. Vaughan', 'role': 'writer'},
          {'name': 'Fiona Staples', 'role': 'artist'},
        ],
        characters: ['Alana', 'Marko', 'Hazel', 'The Will'],
        genres: ['sci-fi', 'fantasy', 'romance'],
      ),
      testCatalogItem(
        id: 'seed-comic-02',
        kind: 'comic',
        title: 'Saga',
        displayTitle: 'Saga #2',
        synopsis: 'Alana and Marko flee with their newborn daughter.',
        publisher: 'Image Comics',
        releaseYear: 2012,
        releaseDate: DateTime.utc(2012, 4, 11),
        itemNumber: '2',
        sortKey: 'saga-0002',
        series: const CatalogSeriesDetailsDto(
          seriesId: 'seed-series-saga',
          seriesTitle: 'Saga',
          volumeNumber: '2',
        ),
        publishing: const CatalogPublishingDetailsDto(
          pageCount: 32,
          coverPriceCents: 299,
          currency: 'USD',
        ),
        creators: [
          {'name': 'Brian K. Vaughan', 'role': 'writer'},
          {'name': 'Fiona Staples', 'role': 'artist'},
        ],
        characters: ['Alana', 'Marko', 'The Stalk'],
        genres: ['sci-fi', 'fantasy'],
      ),
      testCatalogItem(
        id: 'seed-comic-03',
        kind: 'comic',
        title: 'Watchmen',
        synopsis:
            'In an alternate 1985, costumed heroes investigate one of their own\'s murder.',
        publisher: 'DC Comics',
        releaseYear: 1986,
        releaseDate: DateTime.utc(1986, 9, 1),
        itemNumber: '1',
        sortKey: 'watchmen-0001',
        series: const CatalogSeriesDetailsDto(
          seriesId: 'seed-series-watchmen',
          seriesTitle: 'Watchmen',
          volumeName: 'Watchmen',
          volumeNumber: '1',
          volumeStartYear: 1986,
          tags: 'superhero, deconstruction, political',
        ),
        publishing: const CatalogPublishingDetailsDto(
          pageCount: 32,
          coverPriceCents: 150,
          currency: 'USD',
          imprint: 'DC',
        ),
        creators: [
          {'name': 'Alan Moore', 'role': 'writer'},
          {'name': 'Dave Gibbons', 'role': 'artist'},
        ],
        characters: [
          'Rorschach',
          'Dr. Manhattan',
          'Nite Owl',
          'Ozymandias',
        ],
        genres: ['superhero', 'deconstruction'],
      ),
      testCatalogItem(
        id: 'seed-comic-04',
        kind: 'comic',
        title: 'Sandman',
        synopsis:
            'Morpheus, the king of dreams, is captured and held prisoner for decades.',
        publisher: 'DC Comics',
        releaseYear: 1989,
        releaseDate: DateTime.utc(1989, 1, 1),
        itemNumber: '1',
        sortKey: 'sandman-0001',
        series: const CatalogSeriesDetailsDto(
          seriesId: 'seed-series-sandman',
          seriesTitle: 'The Sandman',
          volumeNumber: '1',
          tags: 'dark-fantasy, supernatural',
        ),
        publishing: const CatalogPublishingDetailsDto(
          pageCount: 40,
          imprint: 'Vertigo',
        ),
        creators: [
          {'name': 'Neil Gaiman', 'role': 'writer'},
          {'name': 'Sam Kieth', 'role': 'artist'},
        ],
        characters: ['Morpheus', 'Death', 'Lucifer'],
        genres: ['fantasy', 'horror', 'mythology'],
      ),
      testCatalogItem(
        id: 'seed-comic-05',
        kind: 'comic',
        title: 'Maus',
        synopsis:
            'A graphic novel about the Holocaust, told through anthropomorphic animals.',
        publisher: 'Pantheon Books',
        releaseYear: 1986,
        releaseDate: DateTime.utc(1986, 1, 1),
        sortKey: 'maus-0001',
        publishing: const CatalogPublishingDetailsDto(pageCount: 296),
        creators: [
          {'name': 'Art Spiegelman', 'role': 'writer'},
          {'name': 'Art Spiegelman', 'role': 'artist'},
        ],
        characters: ['Vladek Spiegelman', 'Art Spiegelman'],
        genres: ['biography', 'historical', 'graphic novel'],
      ),
      testCatalogItem(
        id: 'seed-comic-06',
        kind: 'comic',
        title: 'Batman: The Killing Joke',
        synopsis:
            'The Joker\'s attempt to prove that anyone can be driven insane.',
        publisher: 'DC Comics',
        releaseYear: 1988,
        releaseDate: DateTime.utc(1988, 3, 1),
        sortKey: 'batman-killing-joke-0001',
        publishing: const CatalogPublishingDetailsDto(
          pageCount: 64,
          coverPriceCents: 350,
          currency: 'USD',
          imprint: 'DC',
        ),
        creators: [
          {'name': 'Alan Moore', 'role': 'writer'},
          {'name': 'Brian Bolland', 'role': 'artist'},
        ],
        characters: ['Batman', 'The Joker', 'Barbara Gordon'],
        genres: ['superhero', 'psychological'],
      ),
      testCatalogItem(
        id: 'seed-comic-07',
        kind: 'comic',
        title: 'Invincible',
        synopsis:
            'Mark Grayson inherits his father\'s superpowers and discovers the truth about his heritage.',
        publisher: 'Image Comics',
        releaseYear: 2003,
        releaseDate: DateTime.utc(2003, 1, 22),
        itemNumber: '1',
        sortKey: 'invincible-0001',
        series: const CatalogSeriesDetailsDto(
          seriesId: 'seed-series-invincible',
          seriesTitle: 'Invincible',
          volumeNumber: '1',
          volumeStartYear: 2003,
        ),
        publishing: const CatalogPublishingDetailsDto(
          pageCount: 24,
          coverPriceCents: 295,
          currency: 'USD',
        ),
        creators: [
          {'name': 'Robert Kirkman', 'role': 'writer'},
          {'name': 'Cory Walker', 'role': 'artist'},
        ],
        characters: ['Mark Grayson', 'Nolan Grayson', 'Atom Eve'],
        genres: ['superhero', 'action'],
      ),
      testCatalogItem(
        id: 'seed-comic-08',
        kind: 'comic',
        title: 'Y: The Last Man',
        synopsis:
            'The only male survivor of a global androcide must navigate the new world.',
        publisher: 'DC Comics',
        releaseYear: 2002,
        releaseDate: DateTime.utc(2002, 9, 1),
        itemNumber: '1',
        sortKey: 'y-last-man-0001',
        publishing: const CatalogPublishingDetailsDto(
          pageCount: 24,
          imprint: 'Vertigo',
        ),
        creators: [
          {'name': 'Brian K. Vaughan', 'role': 'writer'},
          {'name': 'Pia Guerra', 'role': 'artist'},
        ],
        characters: ['Yorick Brown', 'Agent 355', 'Ampersand'],
        genres: ['sci-fi', 'post-apocalyptic'],
      ),
      testCatalogItem(
        id: 'seed-comic-09',
        kind: 'comic',
        title: 'Bone',
        synopsis:
            'Three cousins from Boneville are lost in a vast desert and stumble upon a mysterious valley.',
        publisher: 'Cartoon Books',
        releaseYear: 1991,
        releaseDate: DateTime.utc(1991, 7, 1),
        itemNumber: '1',
        sortKey: 'bone-0001',
        publishing: const CatalogPublishingDetailsDto(pageCount: 28),
        creators: [
          {'name': 'Jeff Smith', 'role': 'writer'},
          {'name': 'Jeff Smith', 'role': 'artist'},
        ],
        characters: ['Fone Bone', 'Phoney Bone', 'Thorn'],
        genres: ['fantasy', 'adventure', 'comedy'],
      ),
      testCatalogItem(
        id: 'seed-comic-10',
        kind: 'comic',
        title: 'Hellboy: Seed of Destruction',
        synopsis:
            'Hellboy investigates the mystery of his own origin in his first full-length story.',
        publisher: 'Dark Horse Comics',
        releaseYear: 1994,
        releaseDate: DateTime.utc(1994, 3, 1),
        itemNumber: '1',
        sortKey: 'hellboy-0001',
        series: const CatalogSeriesDetailsDto(
          seriesId: 'seed-series-hellboy',
          seriesTitle: 'Hellboy',
          volumeNumber: '1',
          volumeStartYear: 1994,
        ),
        publishing: const CatalogPublishingDetailsDto(
          pageCount: 32,
          coverPriceCents: 295,
          currency: 'USD',
        ),
        creators: [
          {'name': 'Mike Mignola', 'role': 'writer'},
          {'name': 'Mike Mignola', 'role': 'artist'},
        ],
        characters: ['Hellboy', 'Abe Sapien', 'Rasputin'],
        genres: ['horror', 'occult', 'action'],
      ),
    ];

List<OwnedItem> comicSeedOwnedItems(DateTime now) => [
      OwnedItem(
        id: 'seed-owned-comic-01',
        catalogRef: seedCatalogRef('seed-comic-01'),
        createdAt: now.subtract(const Duration(days: 900)),
        updatedAt: now,
        isDigital: false,
        condition: 'Near Mint',
        grade: '9.4',
        pricePaidCents: 499,
        currency: 'USD',
        rating: 9,
        readStatus: 'completed',
        marketValueCents: 15000,
        details: ComicOwnedDetails(
          rawOrSlabbed: 'raw',
          keyComic: true,
          keyReason: 'First printing, first appearance of Saga characters',
          keyCategory: 'first_appearance',
          keySeverity: 'major',
          coverPriceCents: 299,
          lastBagBoardDate: DateTime.utc(2024, 6, 1),
        ),
      ),
      OwnedItem(
        id: 'seed-owned-comic-03',
        catalogRef: seedCatalogRef('seed-comic-03'),
        createdAt: now.subtract(const Duration(days: 1200)),
        updatedAt: now,
        isDigital: false,
        condition: 'Very Good',
        grade: '8.0',
        pricePaidCents: 8500,
        currency: 'USD',
        rating: 10,
        readStatus: 'completed',
        marketValueCents: 35000,
        details: const ComicOwnedDetails(
          rawOrSlabbed: 'slabbed',
          gradingCompany: 'CGC',
          certificationNumber: '1234567890',
          keyComic: true,
          keyReason: 'Iconic first issue of Watchmen',
          keyCategory: 'first_issue',
          keySeverity: 'major',
          coverPriceCents: 150,
        ),
      ),
    ];

List<TrackingEntry> comicSeedTrackingEntries(DateTime now) => [
      TrackingEntry(
        id: 'seed-track-05',
        catalogRef: seedCatalogRef('seed-comic-01'),
        ownedItemId: 'seed-owned-comic-01',
        sourceType: TrackingSourceType.physical,
        status: MediaTrackingStatus.completed,
        rating: 9,
        timesCompleted: 2,
        updatedAt: now,
      ),
    ];
