import 'package:collectarr_app/core/api/dto/catalog/catalog_item_dto.dart';
import 'package:collectarr_app/core/models/owned_item.dart';
import 'package:collectarr_app/core/models/tracking_entry.dart';
import 'package:collectarr_app/core/models/tracking_source.dart';
import 'package:collectarr_app/core/models/tracking_status.dart';
import 'package:collectarr_app/dev/seeds/seed_helpers.dart';
import 'package:collectarr_app/test/helpers/test_data_factories.dart';

List<CatalogItem> movieSeedCatalogItems() => [
      testCatalogItem(
        id: 'seed-movie-01',
        kind: 'movie',
        title: 'Batman Begins',
        displayTitle: 'Batman Begins (2005)',
        synopsis:
            'After witnessing his parents\' murder, Bruce Wayne trains to become a symbol of justice.',
        publisher: 'Warner Bros.',
        releaseYear: 2005,
        releaseDate: DateTime.utc(2005, 6, 15),
        coverImageUrl: 'https://placehold.co/300x450?text=Batman+Begins',
        thumbnailImageUrl: 'https://placehold.co/100x150?text=BB',
        editionTitle: '4K UHD',
        physicalFormat: '4K UHD',
        physicalFormatLabel: '4K Ultra HD Blu-ray',
        barcode: '012569593763',
        variant: '4K UHD',
        country: 'US',
        language: 'en',
        ageRating: 'PG-13',
        sortKey: 'dark-knight-trilogy-0001',
        itemNumber: '1',
        series: const CatalogSeriesDetailsDto(
          seriesId: 'seed-series-dark-knight',
          seriesTitle: 'The Dark Knight Trilogy',
          volumeName: 'The Dark Knight Trilogy',
          volumeNumber: '1',
          volumeStartYear: 2005,
          tags: 'superhero, action, thriller, origin story',
        ),
        video: const VideoCatalogDetails(
          runtimeMinutes: 140,
          color: 'Color',
          nrDiscs: 1,
          screenRatio: '2.39:1',
          audioTracks: 'English DTS-HD MA 5.1, French DD 5.1',
          subtitles: 'English SDH, French, Spanish',
        ),
        publishing: const CatalogPublishingDetailsDto(
          coverPriceCents: 2999,
          currency: 'USD',
          imprint: 'DC Films',
        ),
        creators: [
          {'name': 'Christopher Nolan', 'role': 'director'},
          {'name': 'Hans Zimmer', 'role': 'composer'},
          {'name': 'David S. Goyer', 'role': 'writer'},
        ],
        characters: ['Bruce Wayne', 'Ra\'s al Ghul', 'Alfred Pennyworth'],
        storyArcs: ['Batman\'s Origin'],
        genres: ['superhero', 'action', 'thriller'],
        editions: [
          CatalogEdition(
            id: 'seed-ed-bb-dvd',
            title: 'DVD',
            format: 'DVD',
            publisher: 'Warner Bros.',
            releaseDate: DateTime.utc(2005, 10, 18),
            region: 'US',
            variants: [
              CatalogVariant(
                id: 'seed-var-bb-dvd',
                name: 'DVD',
                variantType: 'physical',
                coverPriceCents: 1999,
                currency: 'USD',
                barcode: '012569593763',
              ),
            ],
          ),
          CatalogEdition(
            id: 'seed-ed-bb-4k',
            title: '4K UHD',
            format: '4K UHD',
            publisher: 'Warner Bros.',
            releaseDate: DateTime.utc(2017, 12, 19),
            region: 'US',
            variants: [
              CatalogVariant(
                id: 'seed-var-bb-4k',
                name: '4K UHD',
                variantType: 'physical',
                coverPriceCents: 2999,
                currency: 'USD',
                isPrimary: true,
              ),
            ],
          ),
        ],
      ),
      testCatalogItem(
        id: 'seed-movie-02',
        kind: 'movie',
        title: 'The Dark Knight',
        synopsis:
            'Batman faces the Joker, a criminal mastermind who seeks to plunge Gotham into anarchy.',
        publisher: 'Warner Bros.',
        releaseYear: 2008,
        releaseDate: DateTime.utc(2008, 7, 18),
        editionTitle: 'Blu-ray',
        physicalFormat: 'Blu-ray',
        country: 'US',
        language: 'en',
        ageRating: 'PG-13',
        sortKey: 'dark-knight-trilogy-0002',
        itemNumber: '2',
        series: const CatalogSeriesDetailsDto(
          seriesId: 'seed-series-dark-knight',
          seriesTitle: 'The Dark Knight Trilogy',
          volumeName: 'The Dark Knight Trilogy',
          volumeNumber: '1',
          volumeStartYear: 2005,
        ),
        video: const VideoCatalogDetails(runtimeMinutes: 152),
        creators: [
          {'name': 'Christopher Nolan', 'role': 'director'},
          {'name': 'Heath Ledger', 'role': 'actor'},
        ],
        characters: ['Bruce Wayne', 'The Joker', 'Harvey Dent'],
        genres: ['superhero', 'crime', 'thriller'],
      ),
      testCatalogItem(
        id: 'seed-movie-03',
        kind: 'movie',
        title: 'Blade Runner',
        synopsis:
            'A blade runner must pursue and terminate four replicants who have returned to Earth.',
        publisher: 'Warner Bros.',
        releaseYear: 1982,
        releaseDate: DateTime.utc(1982, 6, 25),
        editionTitle: 'The Final Cut',
        physicalFormat: 'Blu-ray',
        country: 'US',
        language: 'en',
        ageRating: 'R',
        sortKey: 'blade-runner-0001',
        itemNumber: '1',
        series: const CatalogSeriesDetailsDto(
          seriesId: 'seed-series-blade-runner',
          seriesTitle: 'Blade Runner',
          tags: 'sci-fi, noir, dystopia, cyberpunk',
        ),
        video: const VideoCatalogDetails(
            runtimeMinutes: 117, screenRatio: '2.39:1'),
        creators: [
          {'name': 'Ridley Scott', 'role': 'director'},
          {'name': 'Vangelis', 'role': 'composer'},
        ],
        characters: ['Rick Deckard', 'Roy Batty', 'Rachael'],
        storyArcs: ['Replicant Hunt'],
        genres: ['sci-fi', 'noir'],
      ),
      testCatalogItem(
        id: 'seed-movie-04',
        kind: 'movie',
        title: 'Interstellar',
        synopsis:
            'A team of explorers travel through a wormhole in space to ensure humanity\'s survival.',
        publisher: 'Paramount Pictures',
        releaseYear: 2014,
        releaseDate: DateTime.utc(2014, 11, 7),
        physicalFormat: 'Blu-ray',
        country: 'US',
        language: 'en',
        sortKey: 'interstellar-0001',
        series: const CatalogSeriesDetailsDto(
          seriesId: 'seed-series-interstellar',
          seriesTitle: 'Interstellar',
        ),
        video: const VideoCatalogDetails(runtimeMinutes: 169),
        creators: [
          {'name': 'Christopher Nolan', 'role': 'director'},
          {'name': 'Hans Zimmer', 'role': 'composer'},
        ],
        characters: ['Cooper', 'Murph', 'Dr. Brand'],
        genres: ['sci-fi', 'drama', 'space'],
      ),
      testCatalogItem(
        id: 'seed-movie-05',
        kind: 'movie',
        title: 'Mad Max: Fury Road',
        synopsis:
            'In a post-apocalyptic wasteland, Max teams up with Furiosa to escape a tyrannical warlord.',
        publisher: 'Warner Bros.',
        releaseYear: 2015,
        releaseDate: DateTime.utc(2015, 5, 15),
        country: 'US',
        ageRating: 'R',
        sortKey: 'mad-max-0004',
        video: const VideoCatalogDetails(runtimeMinutes: 120),
        creators: [
          {'name': 'George Miller', 'role': 'director'},
        ],
        characters: ['Max Rockatansky', 'Furiosa', 'Immortan Joe'],
        genres: ['action', 'post-apocalyptic'],
      ),
      testCatalogItem(
        id: 'seed-movie-06',
        kind: 'movie',
        title: 'Alien',
        synopsis:
            'The crew of a commercial spacecraft encounters a deadly lifeform after investigating a distress signal.',
        publisher: '20th Century Fox',
        releaseYear: 1979,
        releaseDate: DateTime.utc(1979, 5, 25),
        country: 'US',
        ageRating: 'R',
        sortKey: 'alien-0001',
        video: const VideoCatalogDetails(runtimeMinutes: 117),
        creators: [
          {'name': 'Ridley Scott', 'role': 'director'},
          {'name': 'Dan O\'Bannon', 'role': 'writer'},
        ],
        characters: ['Ellen Ripley', 'Xenomorph', 'Dallas'],
        storyArcs: ['Xenomorph Saga'],
        genres: ['sci-fi', 'horror'],
      ),
      testCatalogItem(
        id: 'seed-movie-07',
        kind: 'movie',
        title: 'Aliens',
        synopsis:
            'Ripley returns to the planet where her crew encountered the hostile alien creature.',
        publisher: '20th Century Fox',
        releaseYear: 1986,
        releaseDate: DateTime.utc(1986, 7, 18),
        country: 'US',
        ageRating: 'R',
        sortKey: 'alien-0002',
        video: const VideoCatalogDetails(runtimeMinutes: 137),
        creators: [
          {'name': 'James Cameron', 'role': 'director'},
        ],
        characters: ['Ellen Ripley', 'Newt', 'Xenomorph Queen'],
        storyArcs: ['Xenomorph Saga'],
        genres: ['sci-fi', 'action', 'horror'],
      ),
      testCatalogItem(
        id: 'seed-movie-08',
        kind: 'movie',
        title: 'The Matrix',
        synopsis:
            'A computer hacker learns about the true nature of reality and his role in the war against its controllers.',
        publisher: 'Warner Bros.',
        releaseYear: 1999,
        releaseDate: DateTime.utc(1999, 3, 31),
        editionTitle: '4K UHD',
        physicalFormat: '4K UHD',
        barcode: '883929567553',
        country: 'US',
        language: 'en',
        ageRating: 'R',
        sortKey: 'the-matrix-0001',
        video: const VideoCatalogDetails(runtimeMinutes: 136),
        creators: [
          {'name': 'The Wachowskis', 'role': 'director'},
          {'name': 'Keanu Reeves', 'role': 'actor'},
        ],
        characters: ['Neo', 'Morpheus', 'Agent Smith', 'Trinity'],
        genres: ['sci-fi', 'action', 'cyberpunk'],
      ),
      testCatalogItem(
        id: 'seed-movie-09',
        kind: 'movie',
        title: 'The Dark Knight Rises',
        synopsis:
            'Eight years after the Joker\'s reign, Bane forces Batman out of exile.',
        publisher: 'Warner Bros.',
        releaseYear: 2012,
        releaseDate: DateTime.utc(2012, 7, 20),
        country: 'US',
        ageRating: 'PG-13',
        sortKey: 'dark-knight-trilogy-0003',
        itemNumber: '3',
        series: const CatalogSeriesDetailsDto(
          seriesId: 'seed-series-dark-knight',
          seriesTitle: 'The Dark Knight Trilogy',
          volumeNumber: '1',
          volumeStartYear: 2005,
        ),
        video: const VideoCatalogDetails(runtimeMinutes: 165),
        creators: [
          {'name': 'Christopher Nolan', 'role': 'director'},
          {'name': 'Tom Hardy', 'role': 'actor'},
        ],
        characters: ['Bruce Wayne', 'Bane', 'Selina Kyle'],
        genres: ['superhero', 'action'],
      ),
      testCatalogItem(
        id: 'seed-movie-10',
        kind: 'movie',
        title: 'Blade Runner 2049',
        synopsis:
            'A young blade runner\'s discovery of a secret leads him to seek out the former blade runner.',
        publisher: 'Columbia Pictures',
        releaseYear: 2017,
        releaseDate: DateTime.utc(2017, 10, 6),
        country: 'US',
        ageRating: 'R',
        sortKey: 'blade-runner-0002',
        series: const CatalogSeriesDetailsDto(
          seriesId: 'seed-series-blade-runner',
          seriesTitle: 'Blade Runner',
        ),
        video: const VideoCatalogDetails(runtimeMinutes: 164),
        creators: [
          {'name': 'Denis Villeneuve', 'role': 'director'},
          {'name': 'Roger Deakins', 'role': 'cinematographer'},
        ],
        characters: ['Officer K', 'Rick Deckard', 'Niander Wallace'],
        genres: ['sci-fi', 'noir', 'cyberpunk'],
      ),
    ];

List<OwnedItem> movieSeedOwnedItems(DateTime now) => [
      OwnedItem(
        id: 'seed-owned-movie-01',
        catalogRef: seedCatalogRef('seed-movie-01'),
        createdAt: now.subtract(const Duration(days: 365)),
        updatedAt: now,
        isDigital: false,
        condition: 'Near Mint',
        purchaseDate: DateTime.utc(2018, 6, 1),
        pricePaidCents: 2999,
        currency: 'USD',
        personalNotes: 'First 4K UHD purchase',
        quantity: 1,
        rating: 9,
        readStatus: 'completed',
        finishedAt: DateTime.utc(2018, 6, 5),
        purchaseStore: 'Amazon',
        details: const MovieOwnedDetails(
          region: 'Region A',
          packaging: 'Keep Case',
          distributor: 'Universal Pictures',
        ),
        collectionStatus: 'collected',
      ),
      OwnedItem(
        id: 'seed-owned-movie-02',
        catalogRef: seedCatalogRef('seed-movie-02'),
        createdAt: now.subtract(const Duration(days: 300)),
        updatedAt: now,
        isDigital: false,
        condition: 'Mint',
        pricePaidCents: 3499,
        currency: 'USD',
        rating: 10,
        readStatus: 'completed',
        purchaseStore: 'Best Buy',
      ),
    ];

List<TrackingEntry> movieSeedTrackingEntries(DateTime now) => [
      TrackingEntry(
        id: 'seed-track-01',
        catalogRef: seedCatalogRef('seed-movie-01'),
        ownedItemId: 'seed-owned-movie-01',
        sourceType: TrackingSourceType.physical,
        status: MediaTrackingStatus.completed,
        rating: 9,
        startedAt: DateTime.utc(2018, 6, 5),
        finishedAt: DateTime.utc(2018, 6, 5),
        timesCompleted: 3,
        notes: 'Rewatched annually',
        updatedAt: now,
      ),
      TrackingEntry(
        id: 'seed-track-07',
        catalogRef: seedCatalogRef('seed-movie-04'),
        sourceType: TrackingSourceType.streaming,
        status: MediaTrackingStatus.completed,
        rating: 10,
        timesCompleted: 2,
        finishedAt: DateTime.utc(2024, 12, 20),
        updatedAt: now,
      ),
    ];
