import 'package:collectarr_app/core/api/dto/catalog/catalog_item_dto.dart';
import 'package:collectarr_app/core/models/owned_item.dart';
import 'package:collectarr_app/core/models/tracking_entry.dart';
import 'package:collectarr_app/core/models/tracking_source.dart';
import 'package:collectarr_app/core/models/tracking_status.dart';
import 'package:collectarr_app/dev/seeds/seed_helpers.dart';
import 'package:collectarr_app/dev/seeds/seed_catalog_item_factory.dart';

List<CatalogItem> movieSeedCatalogItems() => [
      seedCatalogItem(
        id: 'seed-movie-01',
        kind: 'movie',
        title: 'Batman Begins',
        displayTitle: 'Batman Begins (2005)',
        synopsis:
            'After witnessing his parents\' murder, Bruce Wayne trains with the League of Shadows before returning to Gotham to fight crime as Batman.',
        publisher: 'Warner Bros.',
        releaseYear: 2005,
        releaseDate: DateTime.utc(2005, 6, 15),
        coverImageUrl:
            'https://image.tmdb.org/t/p/w500/1P3QtW1IkivqDrAVNxLRIwIZx97.jpg',
        thumbnailImageUrl:
            'https://image.tmdb.org/t/p/w500/1P3QtW1IkivqDrAVNxLRIwIZx97.jpg',
        editionTitle: '4K Ultra HD + Blu-ray',
        physicalFormat: '4K UHD',
        physicalFormatLabel: '4K Ultra HD Blu-ray',
        barcode: '012569593763',
        variant: 'Steelbook 4K',
        country: 'US',
        language: 'en',
        ageRating: 'PG-13',
        sortKey: 'dark-knight-0001',
        itemNumber: '1',
        series: const CatalogSeriesDetailsDto(
          seriesId: 'seed-series-dark-knight',
          seriesTitle: 'The Dark Knight Trilogy',
          volumeName: 'The Dark Knight Trilogy',
          volumeNumber: '1',
          volumeStartYear: 2005,
          tags: 'superhero, action, thriller, dc comics',
        ),
        video: const VideoCatalogDetails(
          runtimeMinutes: 140,
          color: 'Color',
          nrDiscs: 2,
          screenRatio: '2.39:1',
          audioTracks: 'English DTS-HD MA 5.1, French DD 5.1, Spanish DD 5.1',
          subtitles: 'English SDH, French, Spanish',
          layers: 'Dual Layer (BD-66 + BD-50)',
        ),
        publishing: const CatalogPublishingDetailsDto(
          coverPriceCents: 2999,
          currency: 'USD',
          imprint: 'DC Films',
        ),
        creators: [
          {'name': 'Christopher Nolan', 'role': 'director'},
          {'name': 'Hans Zimmer', 'role': 'composer'},
          {'name': 'David S. Goyer', 'role': 'writer'},
          {'name': 'Christian Bale', 'role': 'actor'},
        ],
        characters: [
          'Bruce Wayne',
          'Ra\'s al Ghul',
          'Alfred Pennyworth',
          'Rachel Dawes'
        ],
        storyArcs: ['Batman Origin'],
        genres: ['superhero', 'action', 'thriller', 'crime'],
        editions: [
          CatalogEdition(
            id: 'seed-ed-bb-4k',
            title: '4K Ultra HD + Blu-ray',
            format: '4K UHD',
            publisher: 'Warner Bros.',
            releaseDate: DateTime.utc(2017, 12, 19),
            region: 'Region Free',
            discs: const [
              CatalogDiscDto(discNumber: 1, name: '4K Feature Film'),
              CatalogDiscDto(discNumber: 2, name: 'Blu-ray Feature + Extras'),
            ],
            variants: [
              CatalogVariant(
                id: 'seed-var-bb-4k',
                name: 'Steelbook 4K UHD',
                variantType: 'physical',
                coverPriceCents: 3499,
                currency: 'USD',
                isPrimary: true,
                barcode: '883929621415',
              ),
            ],
          ),
          CatalogEdition(
            id: 'seed-ed-bb-bluray',
            title: 'Standard Blu-ray Edition',
            format: 'Blu-ray',
            publisher: 'Warner Bros.',
            releaseDate: DateTime.utc(2008, 7, 8),
            region: 'Region A',
            discs: const [
              CatalogDiscDto(
                  discNumber: 1, name: 'Feature Film + Genesis of the Bat'),
            ],
          ),
        ],
      ),
      seedCatalogItem(
        id: 'seed-movie-02',
        kind: 'movie',
        title: 'The Dark Knight',
        displayTitle: 'The Dark Knight (2008)',
        synopsis:
            'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
        publisher: 'Warner Bros.',
        releaseYear: 2008,
        releaseDate: DateTime.utc(2008, 7, 18),
        coverImageUrl:
            'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
        thumbnailImageUrl:
            'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
        editionTitle: 'Collector\'s Edition 4K UHD',
        physicalFormat: '4K UHD',
        physicalFormatLabel: '4K Ultra HD Blu-ray',
        barcode: '883929621422',
        variant: '4K UHD',
        country: 'US',
        language: 'en',
        ageRating: 'PG-13',
        sortKey: 'dark-knight-0002',
        itemNumber: '2',
        series: const CatalogSeriesDetailsDto(
          seriesId: 'seed-series-dark-knight',
          seriesTitle: 'The Dark Knight Trilogy',
          volumeName: 'The Dark Knight Trilogy',
          volumeNumber: '2',
          volumeStartYear: 2005,
          tags: 'superhero, action, thriller, dc comics',
        ),
        video: const VideoCatalogDetails(
          runtimeMinutes: 152,
          color: 'Color',
          nrDiscs: 3,
          screenRatio: '1.78:1 / 2.39:1 (IMAX)',
          audioTracks: 'English DTS-HD MA 5.1, French DD 5.1',
          subtitles: 'English SDH, French, Spanish',
          layers: 'BD-66 + 2x BD-50',
        ),
        publishing: const CatalogPublishingDetailsDto(
          coverPriceCents: 3299,
          currency: 'USD',
          imprint: 'DC Films',
        ),
        creators: [
          {'name': 'Christopher Nolan', 'role': 'director'},
          {'name': 'Heath Ledger', 'role': 'actor'},
          {'name': 'Christian Bale', 'role': 'actor'},
          {'name': 'Hans Zimmer', 'role': 'composer'},
        ],
        characters: ['Bruce Wayne', 'The Joker', 'Harvey Dent', 'Jim Gordon'],
        storyArcs: ['Fall of Harvey Dent'],
        genres: ['superhero', 'crime', 'thriller', 'drama'],
        editions: [
          CatalogEdition(
            id: 'seed-ed-tdk-4k',
            title: '4K Ultra HD 3-Disc Set',
            format: '4K UHD',
            publisher: 'Warner Bros.',
            releaseDate: DateTime.utc(2017, 12, 19),
            region: 'Region Free',
            discs: const [
              CatalogDiscDto(
                  discNumber: 1, name: '4K Feature Film (IMAX Sequences)'),
              CatalogDiscDto(discNumber: 2, name: 'Blu-ray Feature Film'),
              CatalogDiscDto(
                  discNumber: 3, name: 'Bonus Features & Gotham Tonight'),
            ],
          ),
        ],
      ),
      seedCatalogItem(
        id: 'seed-movie-03',
        kind: 'movie',
        title: 'The Dark Knight Rises',
        displayTitle: 'The Dark Knight Rises (2012)',
        synopsis:
            'Eight years after the Joker\'s reign of anarchy, Batman, with the help of the enigmatic Selina Kyle, is forced from his exile to save Gotham City from the brutal guerrilla terrorist Bane.',
        publisher: 'Warner Bros.',
        releaseYear: 2012,
        releaseDate: DateTime.utc(2012, 7, 20),
        coverImageUrl:
            'https://image.tmdb.org/t/p/w500/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg',
        thumbnailImageUrl:
            'https://image.tmdb.org/t/p/w500/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg',
        editionTitle: '4K Ultra HD',
        physicalFormat: '4K UHD',
        barcode: '883929621439',
        variant: '4K UHD',
        country: 'US',
        language: 'en',
        ageRating: 'PG-13',
        sortKey: 'dark-knight-0003',
        itemNumber: '3',
        series: const CatalogSeriesDetailsDto(
          seriesId: 'seed-series-dark-knight',
          seriesTitle: 'The Dark Knight Trilogy',
          volumeName: 'The Dark Knight Trilogy',
          volumeNumber: '3',
          volumeStartYear: 2005,
        ),
        video: const VideoCatalogDetails(
          runtimeMinutes: 165,
          color: 'Color',
          nrDiscs: 3,
          screenRatio: '1.78:1 / 2.39:1 (IMAX)',
          audioTracks: 'English DTS-HD MA 5.1',
          subtitles: 'English SDH, Spanish, French',
        ),
        creators: [
          {'name': 'Christopher Nolan', 'role': 'director'},
          {'name': 'Tom Hardy', 'role': 'actor'},
          {'name': 'Anne Hathaway', 'role': 'actor'},
          {'name': 'Christian Bale', 'role': 'actor'},
        ],
        characters: ['Bruce Wayne', 'Bane', 'Selina Kyle', 'John Blake'],
        genres: ['superhero', 'action', 'thriller'],
      ),
      seedCatalogItem(
        id: 'seed-movie-04',
        kind: 'movie',
        title: 'Inception',
        displayTitle: 'Inception (2010)',
        synopsis:
            'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
        publisher: 'Warner Bros.',
        releaseYear: 2010,
        releaseDate: DateTime.utc(2010, 7, 16),
        coverImageUrl:
            'https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
        thumbnailImageUrl:
            'https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
        editionTitle: '10th Anniversary 4K UHD',
        physicalFormat: '4K UHD',
        barcode: '883929721092',
        country: 'US',
        language: 'en',
        ageRating: 'PG-13',
        sortKey: 'inception-0001',
        video: const VideoCatalogDetails(
          runtimeMinutes: 148,
          color: 'Color',
          nrDiscs: 2,
          screenRatio: '2.39:1',
          audioTracks: 'English DTS-HD MA 5.1, German DD 5.1',
          subtitles: 'English, French, German',
        ),
        creators: [
          {'name': 'Christopher Nolan', 'role': 'director'},
          {'name': 'Leonardo DiCaprio', 'role': 'actor'},
          {'name': 'Elliot Page', 'role': 'actor'},
          {'name': 'Hans Zimmer', 'role': 'composer'},
        ],
        characters: ['Dom Cobb', 'Arthur', 'Ariadne', 'Eames', 'Mal Cobb'],
        genres: ['sci-fi', 'heist', 'action', 'thriller'],
      ),
      seedCatalogItem(
        id: 'seed-movie-05',
        kind: 'movie',
        title: 'Interstellar',
        displayTitle: 'Interstellar (2014)',
        synopsis:
            'When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.',
        publisher: 'Paramount Pictures',
        releaseYear: 2014,
        releaseDate: DateTime.utc(2014, 11, 7),
        coverImageUrl:
            'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        thumbnailImageUrl:
            'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        editionTitle: 'Collector\'s Edition 4K UHD',
        physicalFormat: '4K UHD',
        barcode: '032429298416',
        country: 'US',
        language: 'en',
        ageRating: 'PG-13',
        sortKey: 'interstellar-0001',
        video: const VideoCatalogDetails(
          runtimeMinutes: 169,
          color: 'Color',
          nrDiscs: 3,
          screenRatio: '1.78:1 / 2.39:1 (IMAX)',
          audioTracks: 'English DTS-HD MA 5.1, Spanish DD 5.1',
          subtitles: 'English SDH, Spanish',
        ),
        creators: [
          {'name': 'Christopher Nolan', 'role': 'director'},
          {'name': 'Matthew McConaughey', 'role': 'actor'},
          {'name': 'Anne Hathaway', 'role': 'actor'},
          {'name': 'Jessica Chastain', 'role': 'actor'},
          {'name': 'Hans Zimmer', 'role': 'composer'},
        ],
        characters: ['Cooper', 'Murph', 'Dr. Amelia Brand', 'TARS'],
        genres: ['sci-fi', 'drama', 'adventure'],
      ),
      seedCatalogItem(
        id: 'seed-movie-06',
        kind: 'movie',
        title: 'Blade Runner',
        displayTitle: 'Blade Runner: The Final Cut (1982)',
        synopsis:
            'A blade runner must pursue and terminate four replicants who stole a ship in space and have returned to Earth to find their creator.',
        publisher: 'Warner Bros.',
        releaseYear: 1982,
        releaseDate: DateTime.utc(1982, 6, 25),
        coverImageUrl:
            'https://image.tmdb.org/t/p/w500/63N9uy8nd9j7Eog2axPQ8lbr3Wj.jpg',
        thumbnailImageUrl:
            'https://image.tmdb.org/t/p/w500/63N9uy8nd9j7Eog2axPQ8lbr3Wj.jpg',
        editionTitle: 'The Final Cut 4K UHD',
        physicalFormat: '4K UHD',
        barcode: '883929589876',
        variant: 'The Final Cut',
        country: 'US',
        language: 'en',
        ageRating: 'R',
        sortKey: 'blade-runner-0001',
        itemNumber: '1',
        series: const CatalogSeriesDetailsDto(
          seriesId: 'seed-series-blade-runner',
          seriesTitle: 'Blade Runner',
          volumeName: 'Blade Runner',
          volumeNumber: '1',
          volumeStartYear: 1982,
        ),
        video: const VideoCatalogDetails(
          runtimeMinutes: 117,
          color: 'Color',
          nrDiscs: 4,
          screenRatio: '2.39:1',
          audioTracks: 'English Dolby Atmos, English Dolby TrueHD 7.1',
          subtitles: 'English SDH, French, Spanish',
        ),
        creators: [
          {'name': 'Ridley Scott', 'role': 'director'},
          {'name': 'Harrison Ford', 'role': 'actor'},
          {'name': 'Rutger Hauer', 'role': 'actor'},
          {'name': 'Vangelis', 'role': 'composer'},
        ],
        characters: ['Rick Deckard', 'Roy Batty', 'Rachael', 'Gaff'],
        genres: ['sci-fi', 'neo-noir', 'cyberpunk'],
      ),
      seedCatalogItem(
        id: 'seed-movie-07',
        kind: 'movie',
        title: 'Blade Runner 2049',
        displayTitle: 'Blade Runner 2049 (2017)',
        synopsis:
            'Young Blade Runner K\'s discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who\'s been missing for thirty years.',
        publisher: 'Sony Pictures / Warner Bros.',
        releaseYear: 2017,
        releaseDate: DateTime.utc(2017, 10, 6),
        coverImageUrl:
            'https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
        thumbnailImageUrl:
            'https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
        editionTitle: 'Limited Steelbook 4K UHD',
        physicalFormat: '4K UHD',
        barcode: '043396515789',
        variant: 'Steelbook',
        country: 'US',
        language: 'en',
        ageRating: 'R',
        sortKey: 'blade-runner-0002',
        itemNumber: '2',
        series: const CatalogSeriesDetailsDto(
          seriesId: 'seed-series-blade-runner',
          seriesTitle: 'Blade Runner',
          volumeName: 'Blade Runner',
          volumeNumber: '2',
          volumeStartYear: 1982,
        ),
        video: const VideoCatalogDetails(
          runtimeMinutes: 164,
          color: 'Color',
          nrDiscs: 2,
          screenRatio: '2.39:1',
          audioTracks: 'English Dolby Atmos, DTS-HD MA 5.1',
          subtitles: 'English SDH, Spanish',
        ),
        creators: [
          {'name': 'Denis Villeneuve', 'role': 'director'},
          {'name': 'Roger Deakins', 'role': 'cinematographer'},
          {'name': 'Ryan Gosling', 'role': 'actor'},
          {'name': 'Harrison Ford', 'role': 'actor'},
          {'name': 'Hans Zimmer', 'role': 'composer'},
        ],
        characters: [
          'Officer K',
          'Rick Deckard',
          'Joi',
          'Niander Wallace',
          'Luv'
        ],
        genres: ['sci-fi', 'neo-noir', 'cyberpunk', 'mystery'],
      ),
      seedCatalogItem(
        id: 'seed-movie-08',
        kind: 'movie',
        title: 'Pulp Fiction',
        displayTitle: 'Pulp Fiction (1994)',
        synopsis:
            'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
        publisher: 'Miramax / Paramount',
        releaseYear: 1994,
        releaseDate: DateTime.utc(1994, 10, 14),
        coverImageUrl:
            'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
        thumbnailImageUrl:
            'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
        editionTitle: 'Collector\'s 4K Ultra HD',
        physicalFormat: '4K UHD',
        barcode: '191329235072',
        country: 'US',
        language: 'en',
        ageRating: 'R',
        sortKey: 'pulp-fiction-0001',
        video: const VideoCatalogDetails(
          runtimeMinutes: 154,
          color: 'Color',
          nrDiscs: 2,
          screenRatio: '2.35:1',
          audioTracks: 'English DTS-HD MA 5.1',
          subtitles: 'English SDH, Spanish',
        ),
        creators: [
          {'name': 'Quentin Tarantino', 'role': 'director'},
          {'name': 'John Travolta', 'role': 'actor'},
          {'name': 'Samuel L. Jackson', 'role': 'actor'},
          {'name': 'Uma Thurman', 'role': 'actor'},
        ],
        characters: [
          'Vincent Vega',
          'Jules Winnfield',
          'Mia Wallace',
          'Butch Coolidge'
        ],
        genres: ['crime', 'drama', 'thriller'],
      ),
      seedCatalogItem(
        id: 'seed-movie-09',
        kind: 'movie',
        title: 'The Matrix',
        displayTitle: 'The Matrix (1999)',
        synopsis:
            'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.',
        publisher: 'Warner Bros.',
        releaseYear: 1999,
        releaseDate: DateTime.utc(1999, 3, 31),
        coverImageUrl:
            'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
        thumbnailImageUrl:
            'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
        editionTitle: '20th Anniversary 4K UHD',
        physicalFormat: '4K UHD',
        barcode: '883929631629',
        variant: '4K UHD',
        country: 'US',
        language: 'en',
        ageRating: 'R',
        sortKey: 'matrix-0001',
        itemNumber: '1',
        series: const CatalogSeriesDetailsDto(
          seriesId: 'seed-series-matrix',
          seriesTitle: 'The Matrix Franchise',
          volumeName: 'The Matrix',
          volumeNumber: '1',
          volumeStartYear: 1999,
        ),
        video: const VideoCatalogDetails(
          runtimeMinutes: 136,
          color: 'Color',
          nrDiscs: 2,
          screenRatio: '2.39:1',
          audioTracks: 'English Dolby Atmos, TrueHD 7.1',
          subtitles: 'English SDH, French, Spanish',
        ),
        creators: [
          {'name': 'Lilly Wachowski', 'role': 'director'},
          {'name': 'Lana Wachowski', 'role': 'director'},
          {'name': 'Keanu Reeves', 'role': 'actor'},
          {'name': 'Laurence Fishburne', 'role': 'actor'},
          {'name': 'Carrie-Anne Moss', 'role': 'actor'},
        ],
        characters: ['Neo', 'Morpheus', 'Trinity', 'Agent Smith'],
        genres: ['sci-fi', 'action', 'cyberpunk'],
      ),
      seedCatalogItem(
        id: 'seed-movie-10',
        kind: 'movie',
        title: 'Parasite',
        displayTitle: 'Parasite (2019)',
        synopsis:
            'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
        publisher: 'Criterion Collection / Neon',
        releaseYear: 2019,
        releaseDate: DateTime.utc(2019, 5, 30),
        coverImageUrl:
            'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
        thumbnailImageUrl:
            'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
        editionTitle: 'The Criterion Collection Edition',
        physicalFormat: 'Blu-ray',
        barcode: '715515250412',
        variant: 'Criterion #1052',
        country: 'KR',
        language: 'ko',
        ageRating: 'R',
        sortKey: 'parasite-0001',
        video: const VideoCatalogDetails(
          runtimeMinutes: 132,
          color: 'Color & B/W',
          nrDiscs: 2,
          screenRatio: '2.39:1',
          audioTracks: 'Korean Dolby Atmos, Korean DTS-HD MA 5.1',
          subtitles: 'English',
        ),
        creators: [
          {'name': 'Bong Joon-ho', 'role': 'director'},
          {'name': 'Song Kang-ho', 'role': 'actor'},
          {'name': 'Choi Woo-shik', 'role': 'actor'},
          {'name': 'Jung Jae-il', 'role': 'composer'},
        ],
        characters: [
          'Kim Ki-taek',
          'Kim Ki-woo',
          'Kim Ki-jung',
          'Park Dong-ik'
        ],
        genres: ['drama', 'thriller', 'black comedy'],
        editions: [
          CatalogEdition(
            id: 'seed-ed-parasite-criterion',
            title: 'The Criterion Collection #1052',
            format: 'Blu-ray',
            publisher: 'The Criterion Collection',
            releaseDate: DateTime.utc(2020, 10, 27),
            region: 'Region A',
            discs: const [
              CatalogDiscDto(
                  discNumber: 1, name: 'Color Feature Film + Commentary'),
              CatalogDiscDto(
                  discNumber: 2,
                  name: 'Black-and-White Edition + Cannes Masterclass'),
            ],
          ),
        ],
      ),
      seedCatalogItem(
        id: 'seed-movie-11',
        kind: 'movie',
        title: 'Spirited Away',
        displayTitle: 'Spirited Away (2001)',
        synopsis:
            'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.',
        publisher: 'Studio Ghibli / GKIDS',
        releaseYear: 2001,
        releaseDate: DateTime.utc(2001, 7, 20),
        coverImageUrl:
            'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
        thumbnailImageUrl:
            'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
        editionTitle: 'Collector\'s Steelbook Blu-ray',
        physicalFormat: 'Blu-ray',
        barcode: '826663212877',
        country: 'JP',
        language: 'ja',
        ageRating: 'PG',
        sortKey: 'spirited-away-0001',
        video: const VideoCatalogDetails(
          runtimeMinutes: 125,
          color: 'Color',
          nrDiscs: 2,
          screenRatio: '1.85:1',
          audioTracks: 'Japanese DTS-HD MA 5.1, English DTS-HD MA 5.1',
          subtitles: 'English SDH, English, French',
        ),
        creators: [
          {'name': 'Hayao Miyazaki', 'role': 'director'},
          {'name': 'Joe Hisaishi', 'role': 'composer'},
        ],
        characters: ['Chihiro Ogino', 'Haku', 'Yubaba', 'No-Face', 'Kamaji'],
        genres: ['animation', 'fantasy', 'adventure', 'family'],
      ),
      seedCatalogItem(
        id: 'seed-movie-12',
        kind: 'movie',
        title: 'Dune: Part One',
        displayTitle: 'Dune: Part One (2021)',
        synopsis:
            'Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people.',
        publisher: 'Warner Bros. / Legendary',
        releaseYear: 2021,
        releaseDate: DateTime.utc(2021, 10, 22),
        coverImageUrl:
            'https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg',
        thumbnailImageUrl:
            'https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg',
        editionTitle: '4K Ultra HD + Blu-ray',
        physicalFormat: '4K UHD',
        barcode: '883929738410',
        variant: '4K UHD',
        country: 'US',
        language: 'en',
        ageRating: 'PG-13',
        sortKey: 'dune-movie-0001',
        itemNumber: '1',
        series: const CatalogSeriesDetailsDto(
          seriesId: 'seed-series-dune-films',
          seriesTitle: 'Dune Film Saga',
          volumeName: 'Dune',
          volumeNumber: '1',
          volumeStartYear: 2021,
        ),
        video: const VideoCatalogDetails(
          runtimeMinutes: 155,
          color: 'Color',
          nrDiscs: 2,
          screenRatio: '2.39:1',
          audioTracks: 'English Dolby Atmos, Dolby TrueHD 7.1',
          subtitles: 'English SDH, Spanish, French',
        ),
        creators: [
          {'name': 'Denis Villeneuve', 'role': 'director'},
          {'name': 'Greig Fraser', 'role': 'cinematographer'},
          {'name': 'Hans Zimmer', 'role': 'composer'},
          {'name': 'Timothée Chalamet', 'role': 'actor'},
          {'name': 'Rebecca Ferguson', 'role': 'actor'},
        ],
        characters: [
          'Paul Atreides',
          'Lady Jessica',
          'Duke Leto',
          'Duncan Idaho',
          'Chani'
        ],
        genres: ['sci-fi', 'adventure', 'drama'],
      ),
      seedCatalogItem(
        id: 'seed-movie-13',
        kind: 'movie',
        title: 'Dune: Part Two',
        displayTitle: 'Dune: Part Two (2024)',
        synopsis:
            'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, he endeavors to prevent a terrible future.',
        publisher: 'Warner Bros. / Legendary',
        releaseYear: 2024,
        releaseDate: DateTime.utc(2024, 3, 1),
        coverImageUrl:
            'https://image.tmdb.org/t/p/w500/czembW0Rk1Ke7lCJGXBbOhFdqqQ.jpg',
        thumbnailImageUrl:
            'https://image.tmdb.org/t/p/w500/czembW0Rk1Ke7lCJGXBbOhFdqqQ.jpg',
        editionTitle: 'Steelbook 4K UHD',
        physicalFormat: '4K UHD',
        barcode: '883929808397',
        variant: 'Steelbook',
        country: 'US',
        language: 'en',
        ageRating: 'PG-13',
        sortKey: 'dune-movie-0002',
        itemNumber: '2',
        series: const CatalogSeriesDetailsDto(
          seriesId: 'seed-series-dune-films',
          seriesTitle: 'Dune Film Saga',
          volumeName: 'Dune',
          volumeNumber: '2',
          volumeStartYear: 2021,
        ),
        video: const VideoCatalogDetails(
          runtimeMinutes: 166,
          color: 'Color',
          nrDiscs: 2,
          screenRatio: '2.39:1',
          audioTracks: 'English Dolby Atmos, Dolby TrueHD 7.1',
          subtitles: 'English SDH, Spanish',
        ),
        creators: [
          {'name': 'Denis Villeneuve', 'role': 'director'},
          {'name': 'Hans Zimmer', 'role': 'composer'},
          {'name': 'Timothée Chalamet', 'role': 'actor'},
          {'name': 'Zendaya', 'role': 'actor'},
          {'name': 'Austin Butler', 'role': 'actor'},
        ],
        characters: [
          'Paul Atreides',
          'Chani',
          'Feyd-Rautha',
          'Princess Irulan',
          'Stilgar'
        ],
        genres: ['sci-fi', 'adventure', 'action', 'drama'],
      ),
      seedCatalogItem(
        id: 'seed-movie-14',
        kind: 'movie',
        title: 'Oppenheimer',
        displayTitle: 'Oppenheimer (2023)',
        synopsis:
            'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.',
        publisher: 'Universal Pictures',
        releaseYear: 2023,
        releaseDate: DateTime.utc(2023, 7, 21),
        coverImageUrl:
            'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
        thumbnailImageUrl:
            'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
        editionTitle: 'Collector\'s Edition 4K UHD',
        physicalFormat: '4K UHD',
        barcode: '191329244463',
        country: 'US',
        language: 'en',
        ageRating: 'R',
        sortKey: 'oppenheimer-0001',
        video: const VideoCatalogDetails(
          runtimeMinutes: 180,
          color: 'Color & B/W',
          nrDiscs: 3,
          screenRatio: '1.78:1 / 2.20:1 (IMAX)',
          audioTracks: 'English DTS-HD MA 5.1',
          subtitles: 'English SDH, French, Spanish',
        ),
        creators: [
          {'name': 'Christopher Nolan', 'role': 'director'},
          {'name': 'Cillian Murphy', 'role': 'actor'},
          {'name': 'Robert Downey Jr.', 'role': 'actor'},
          {'name': 'Emily Blunt', 'role': 'actor'},
          {'name': 'Ludwig Göransson', 'role': 'composer'},
        ],
        characters: [
          'J. Robert Oppenheimer',
          'Lewis Strauss',
          'Kitty Oppenheimer',
          'Leslie Groves'
        ],
        genres: ['biography', 'drama', 'history'],
      ),
      seedCatalogItem(
        id: 'seed-movie-15',
        kind: 'movie',
        title: 'Spider-Man: Into the Spider-Verse',
        displayTitle: 'Spider-Man: Into the Spider-Verse (2018)',
        synopsis:
            'Teen Miles Morales becomes the new Spider-Man and joins other Spider-Heroes from alternate universes to stop a menace for all realities.',
        publisher: 'Sony Pictures Animation',
        releaseYear: 2018,
        releaseDate: DateTime.utc(2018, 12, 14),
        coverImageUrl:
            'https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg',
        thumbnailImageUrl:
            'https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg',
        editionTitle: '4K Ultra HD + Blu-ray',
        physicalFormat: '4K UHD',
        barcode: '043396541627',
        country: 'US',
        language: 'en',
        ageRating: 'PG',
        sortKey: 'spider-verse-0001',
        itemNumber: '1',
        series: const CatalogSeriesDetailsDto(
          seriesId: 'seed-series-spider-verse',
          seriesTitle: 'Spider-Verse Saga',
          volumeName: 'Spider-Verse',
          volumeNumber: '1',
          volumeStartYear: 2018,
        ),
        video: const VideoCatalogDetails(
          runtimeMinutes: 117,
          color: 'Color',
          nrDiscs: 2,
          screenRatio: '2.39:1',
          audioTracks: 'English Dolby Atmos, DTS-HD MA 5.1',
          subtitles: 'English SDH, Spanish, French',
        ),
        creators: [
          {'name': 'Bob Persichetti', 'role': 'director'},
          {'name': 'Peter Ramsey', 'role': 'director'},
          {'name': 'Rodney Rothman', 'role': 'director'},
          {'name': 'Phil Lord', 'role': 'writer'},
          {'name': 'Daniel Pemberton', 'role': 'composer'},
        ],
        characters: [
          'Miles Morales',
          'Peter B. Parker',
          'Gwen Stacy',
          'Kingpin'
        ],
        genres: ['animation', 'action', 'superhero', 'sci-fi'],
      ),
    ];

List<OwnedItem> movieSeedOwnedItems(DateTime now) => [
      OwnedItem(
        id: 'seed-owned-movie-01',
        catalogRef: seedCatalogRef('seed-movie-01'),
        createdAt: now.subtract(const Duration(days: 420)),
        updatedAt: now,
        isDigital: false,
        condition: 'Near Mint',
        purchaseDate: DateTime.utc(2018, 6, 1),
        pricePaidCents: 3499,
        currency: 'USD',
        personalNotes: 'Steelbook 4K UHD release. Flawless condition.',
        quantity: 1,
        rating: 9,
        readStatus: 'completed',
        finishedAt: DateTime.utc(2018, 6, 5),
        purchaseStore: 'Best Buy',
        details: const MovieOwnedDetails(
          region: 'Region Free',
          packaging: 'Steelbook',
          distributor: 'Warner Bros.',
        ),
        collectionStatus: 'collected',
      ),
      OwnedItem(
        id: 'seed-owned-movie-02',
        catalogRef: seedCatalogRef('seed-movie-02'),
        createdAt: now.subtract(const Duration(days: 380)),
        updatedAt: now,
        isDigital: false,
        condition: 'Mint',
        purchaseDate: DateTime.utc(2018, 7, 10),
        pricePaidCents: 3299,
        currency: 'USD',
        personalNotes: 'Incredible IMAX aspect ratio shifting presentation.',
        rating: 10,
        readStatus: 'completed',
        purchaseStore: 'Amazon',
        details: const MovieOwnedDetails(
          region: 'Region Free',
          packaging: 'Keep Case',
          distributor: 'Warner Bros.',
        ),
        collectionStatus: 'collected',
      ),
      OwnedItem(
        id: 'seed-owned-movie-03',
        catalogRef: seedCatalogRef('seed-movie-03'),
        createdAt: now.subtract(const Duration(days: 350)),
        updatedAt: now,
        isDigital: false,
        condition: 'Near Mint',
        purchaseDate: DateTime.utc(2018, 8, 14),
        pricePaidCents: 3299,
        currency: 'USD',
        personalNotes: 'Final chapter of the trilogy in a 4K keep case.',
        quantity: 1,
        rating: 9,
        readStatus: 'completed',
        purchaseStore: 'Amazon',
        collectionStatus: 'collected',
      ),
      OwnedItem(
        id: 'seed-owned-movie-04',
        catalogRef: seedCatalogRef('seed-movie-04'),
        createdAt: now.subtract(const Duration(days: 280)),
        updatedAt: now,
        isDigital: false,
        condition: 'Near Mint',
        purchaseDate: DateTime.utc(2020, 11, 15),
        pricePaidCents: 2799,
        currency: 'USD',
        personalNotes: '10th Anniversary slipcover edition.',
        rating: 10,
        readStatus: 'completed',
        purchaseStore: 'Zavvi',
        collectionStatus: 'collected',
      ),
      OwnedItem(
        id: 'seed-owned-movie-05',
        catalogRef: seedCatalogRef('seed-movie-05'),
        createdAt: now.subtract(const Duration(days: 200)),
        updatedAt: now,
        isDigital: false,
        condition: 'Mint',
        purchaseDate: DateTime.utc(2021, 3, 22),
        pricePaidCents: 2999,
        currency: 'USD',
        personalNotes:
            'Hans Zimmer pipe organ score sounds breathtaking on 5.1.',
        rating: 10,
        readStatus: 'completed',
        purchaseStore: 'Target',
        collectionStatus: 'collected',
      ),
      OwnedItem(
        id: 'seed-owned-movie-06',
        catalogRef: seedCatalogRef('seed-movie-06'),
        createdAt: now.subtract(const Duration(days: 500)),
        updatedAt: now,
        isDigital: false,
        condition: 'Near Mint',
        purchaseDate: DateTime.utc(2019, 1, 10),
        pricePaidCents: 2499,
        currency: 'USD',
        personalNotes: 'Final Cut Dolby Atmos mix is reference tier.',
        rating: 9,
        readStatus: 'completed',
        purchaseStore: 'Barnes & Noble',
        collectionStatus: 'collected',
      ),
      OwnedItem(
        id: 'seed-owned-movie-07',
        catalogRef: seedCatalogRef('seed-movie-07'),
        createdAt: now.subtract(const Duration(days: 340)),
        updatedAt: now,
        isDigital: false,
        condition: 'Mint',
        purchaseDate: DateTime.utc(2020, 5, 4),
        pricePaidCents: 3999,
        currency: 'USD',
        personalNotes: 'Mondo steelbook with embossed typography.',
        rating: 10,
        readStatus: 'completed',
        purchaseStore: 'Zavvi',
        collectionStatus: 'collected',
      ),
      OwnedItem(
        id: 'seed-owned-movie-08',
        catalogRef: seedCatalogRef('seed-movie-08'),
        createdAt: now.subtract(const Duration(days: 240)),
        updatedAt: now,
        isDigital: false,
        condition: 'Very Good',
        purchaseDate: DateTime.utc(2019, 10, 1),
        pricePaidCents: 2499,
        currency: 'USD',
        personalNotes: 'Special edition with the original mono soundtrack.',
        quantity: 1,
        rating: 10,
        readStatus: 'completed',
        purchaseStore: 'Criterion Store',
        details: const MovieOwnedDetails(
          region: 'Region A',
          packaging: 'Digipak',
          distributor: 'The Criterion Collection',
        ),
        collectionStatus: 'collected',
      ),
      OwnedItem(
        id: 'seed-owned-movie-09',
        catalogRef: seedCatalogRef('seed-movie-09'),
        createdAt: now.subtract(const Duration(days: 230)),
        updatedAt: now,
        isDigital: false,
        condition: 'Near Mint',
        purchaseDate: DateTime.utc(2020, 2, 14),
        pricePaidCents: 2799,
        currency: 'USD',
        personalNotes: '4K restoration with both theatrical cuts.',
        quantity: 1,
        rating: 9,
        readStatus: 'completed',
        purchaseStore: 'Best Buy',
        collectionStatus: 'collected',
      ),
      OwnedItem(
        id: 'seed-owned-movie-10',
        catalogRef: seedCatalogRef('seed-movie-10'),
        createdAt: now.subtract(const Duration(days: 150)),
        updatedAt: now,
        isDigital: false,
        condition: 'Mint',
        purchaseDate: DateTime.utc(2022, 11, 25),
        pricePaidCents: 2999,
        currency: 'USD',
        personalNotes:
            'Criterion 50% off flash sale copy. Includes Black & White cut.',
        rating: 10,
        readStatus: 'completed',
        purchaseStore: 'Criterion Channel Store',
        details: const MovieOwnedDetails(
          region: 'Region A',
          packaging: 'Digipak',
          distributor: 'The Criterion Collection',
        ),
        collectionStatus: 'collected',
      ),
      OwnedItem(
        id: 'seed-owned-movie-11',
        catalogRef: seedCatalogRef('seed-movie-11'),
        createdAt: now.subtract(const Duration(days: 90)),
        updatedAt: now,
        isDigital: false,
        condition: 'Mint',
        purchaseDate: DateTime.utc(2023, 8, 12),
        pricePaidCents: 2199,
        currency: 'USD',
        personalNotes: 'GKIDS steelbook with original theatrical poster art.',
        rating: 10,
        readStatus: 'completed',
        purchaseStore: 'Amazon',
        collectionStatus: 'collected',
      ),
      OwnedItem(
        id: 'seed-owned-movie-12',
        catalogRef: seedCatalogRef('seed-movie-12'),
        createdAt: now.subtract(const Duration(days: 60)),
        updatedAt: now,
        isDigital: false,
        condition: 'Mint',
        purchaseDate: DateTime.utc(2023, 12, 1),
        pricePaidCents: 2999,
        currency: 'USD',
        personalNotes: 'Reference Dolby Vision demo disc.',
        rating: 9,
        readStatus: 'completed',
        purchaseStore: 'Best Buy',
        collectionStatus: 'collected',
      ),
      OwnedItem(
        id: 'seed-owned-movie-13',
        catalogRef: seedCatalogRef('seed-movie-13'),
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now,
        isDigital: false,
        condition: 'Mint',
        purchaseDate: DateTime.utc(2024, 5, 14),
        pricePaidCents: 3799,
        currency: 'USD',
        personalNotes: 'Day 1 preorder steelbook.',
        rating: 10,
        readStatus: 'completed',
        purchaseStore: 'Walmart',
        collectionStatus: 'collected',
      ),
      OwnedItem(
        id: 'seed-owned-movie-14',
        catalogRef: seedCatalogRef('seed-movie-14'),
        createdAt: now.subtract(const Duration(days: 45)),
        updatedAt: now,
        isDigital: false,
        condition: 'Near Mint',
        purchaseDate: DateTime.utc(2024, 2, 20),
        pricePaidCents: 3499,
        currency: 'USD',
        personalNotes: '3-disc set with over 3 hours of special features.',
        rating: 10,
        readStatus: 'completed',
        purchaseStore: 'Target',
        collectionStatus: 'collected',
      ),
      OwnedItem(
        id: 'seed-owned-movie-15',
        catalogRef: seedCatalogRef('seed-movie-15'),
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now,
        isDigital: false,
        condition: 'Mint',
        purchaseDate: DateTime.utc(2024, 6, 18),
        pricePaidCents: 2999,
        currency: 'USD',
        personalNotes: 'Animated 4K collector edition with art cards.',
        quantity: 1,
        rating: 10,
        readStatus: 'completed',
        purchaseStore: 'Sony Pictures Store',
        collectionStatus: 'collected',
      ),
    ];

List<TrackingEntry> movieSeedTrackingEntries(DateTime now) => [
      TrackingEntry(
        id: 'seed-track-movie-01',
        catalogRef: seedCatalogRef('seed-movie-01'),
        ownedItemId: 'seed-owned-movie-01',
        sourceType: TrackingSourceType.physical,
        status: MediaTrackingStatus.completed,
        rating: 9,
        startedAt: DateTime.utc(2018, 6, 5),
        finishedAt: DateTime.utc(2018, 6, 5),
        timesCompleted: 3,
        notes: 'Rewatched annually.',
        updatedAt: now,
      ),
      TrackingEntry(
        id: 'seed-track-movie-02',
        catalogRef: seedCatalogRef('seed-movie-02'),
        ownedItemId: 'seed-owned-movie-02',
        sourceType: TrackingSourceType.physical,
        status: MediaTrackingStatus.completed,
        rating: 10,
        startedAt: DateTime.utc(2018, 7, 12),
        finishedAt: DateTime.utc(2018, 7, 12),
        timesCompleted: 5,
        notes: 'Heath Ledger performance remains unmatched.',
        updatedAt: now,
      ),
      TrackingEntry(
        id: 'seed-track-movie-03',
        catalogRef: seedCatalogRef('seed-movie-03'),
        ownedItemId: 'seed-owned-movie-03',
        sourceType: TrackingSourceType.physical,
        status: MediaTrackingStatus.completed,
        rating: 9,
        startedAt: DateTime.utc(2018, 8, 20),
        finishedAt: DateTime.utc(2018, 8, 20),
        timesCompleted: 2,
        updatedAt: now,
      ),
      TrackingEntry(
        id: 'seed-track-movie-04',
        ownedItemId: 'seed-owned-movie-04',
        catalogRef: seedCatalogRef('seed-movie-04'),
        sourceType: TrackingSourceType.physical,
        status: MediaTrackingStatus.completed,
        rating: 10,
        timesCompleted: 4,
        finishedAt: DateTime.utc(2023, 10, 10),
        updatedAt: now,
      ),
      TrackingEntry(
        id: 'seed-track-movie-07',
        ownedItemId: 'seed-owned-movie-07',
        catalogRef: seedCatalogRef('seed-movie-07'),
        sourceType: TrackingSourceType.physical,
        status: MediaTrackingStatus.completed,
        rating: 10,
        timesCompleted: 3,
        finishedAt: DateTime.utc(2024, 1, 15),
        notes: 'Cinematography masterclass by Roger Deakins.',
        updatedAt: now,
      ),
      TrackingEntry(
        id: 'seed-track-movie-05',
        catalogRef: seedCatalogRef('seed-movie-05'),
        ownedItemId: 'seed-owned-movie-05',
        sourceType: TrackingSourceType.physical,
        status: MediaTrackingStatus.completed,
        rating: 10,
        startedAt: DateTime.utc(2021, 3, 25),
        finishedAt: DateTime.utc(2021, 3, 25),
        timesCompleted: 3,
        updatedAt: now,
      ),
      TrackingEntry(
        id: 'seed-track-movie-06',
        catalogRef: seedCatalogRef('seed-movie-06'),
        ownedItemId: 'seed-owned-movie-06',
        sourceType: TrackingSourceType.physical,
        status: MediaTrackingStatus.completed,
        rating: 9,
        startedAt: DateTime.utc(2019, 1, 15),
        finishedAt: DateTime.utc(2019, 1, 15),
        timesCompleted: 2,
        updatedAt: now,
      ),
      TrackingEntry(
        id: 'seed-track-movie-08',
        catalogRef: seedCatalogRef('seed-movie-08'),
        ownedItemId: 'seed-owned-movie-08',
        sourceType: TrackingSourceType.physical,
        status: MediaTrackingStatus.completed,
        rating: 10,
        startedAt: DateTime.utc(2019, 10, 5),
        finishedAt: DateTime.utc(2019, 10, 5),
        timesCompleted: 4,
        updatedAt: now,
      ),
      TrackingEntry(
        id: 'seed-track-movie-09',
        catalogRef: seedCatalogRef('seed-movie-09'),
        ownedItemId: 'seed-owned-movie-09',
        sourceType: TrackingSourceType.physical,
        status: MediaTrackingStatus.completed,
        rating: 9,
        startedAt: DateTime.utc(2020, 2, 20),
        finishedAt: DateTime.utc(2020, 2, 20),
        timesCompleted: 3,
        updatedAt: now,
      ),
      TrackingEntry(
        id: 'seed-track-movie-10',
        ownedItemId: 'seed-owned-movie-10',
        catalogRef: seedCatalogRef('seed-movie-10'),
        sourceType: TrackingSourceType.physical,
        status: MediaTrackingStatus.completed,
        rating: 10,
        timesCompleted: 2,
        finishedAt: DateTime.utc(2023, 1, 2),
        updatedAt: now,
      ),
      TrackingEntry(
        id: 'seed-track-movie-13',
        ownedItemId: 'seed-owned-movie-13',
        catalogRef: seedCatalogRef('seed-movie-13'),
        sourceType: TrackingSourceType.physical,
        status: MediaTrackingStatus.completed,
        rating: 10,
        timesCompleted: 2,
        finishedAt: DateTime.utc(2024, 3, 3),
        notes: 'Watched in 70mm IMAX.',
        updatedAt: now,
      ),
      TrackingEntry(
        id: 'seed-track-movie-11',
        catalogRef: seedCatalogRef('seed-movie-11'),
        ownedItemId: 'seed-owned-movie-11',
        sourceType: TrackingSourceType.physical,
        status: MediaTrackingStatus.completed,
        rating: 10,
        startedAt: DateTime.utc(2023, 8, 15),
        finishedAt: DateTime.utc(2023, 8, 15),
        timesCompleted: 3,
        updatedAt: now,
      ),
      TrackingEntry(
        id: 'seed-track-movie-12',
        catalogRef: seedCatalogRef('seed-movie-12'),
        ownedItemId: 'seed-owned-movie-12',
        sourceType: TrackingSourceType.physical,
        status: MediaTrackingStatus.completed,
        rating: 9,
        startedAt: DateTime.utc(2023, 12, 8),
        finishedAt: DateTime.utc(2023, 12, 8),
        timesCompleted: 2,
        updatedAt: now,
      ),
      TrackingEntry(
        id: 'seed-track-movie-14',
        catalogRef: seedCatalogRef('seed-movie-14'),
        ownedItemId: 'seed-owned-movie-14',
        sourceType: TrackingSourceType.physical,
        status: MediaTrackingStatus.completed,
        rating: 10,
        startedAt: DateTime.utc(2024, 2, 25),
        finishedAt: DateTime.utc(2024, 2, 25),
        timesCompleted: 2,
        updatedAt: now,
      ),
      TrackingEntry(
        id: 'seed-track-movie-15',
        catalogRef: seedCatalogRef('seed-movie-15'),
        ownedItemId: 'seed-owned-movie-15',
        sourceType: TrackingSourceType.physical,
        status: MediaTrackingStatus.completed,
        rating: 10,
        startedAt: DateTime.utc(2024, 6, 20),
        finishedAt: DateTime.utc(2024, 6, 20),
        timesCompleted: 3,
        updatedAt: now,
      ),
    ];
