import 'package:collectarr_app/features/collection/repositories/pick_list_repository.dart';

Future<void> seedPickLists(PickListRepository repo) async {
  await repo.setValues('conditions', [
    'Mint',
    'Near Mint',
    'Very Fine',
    'Fine',
    'Very Good',
    'Good',
    'Fair',
    'Poor',
  ]);
  await repo.setValues('grades', [
    '10.0',
    '9.8',
    '9.6',
    '9.4',
    '9.2',
    '9.0',
    '8.5',
    '8.0',
    '7.5',
    '7.0',
    '6.5',
    '6.0',
    '5.5',
    '5.0',
  ]);
  await repo.setValues('physical_formats', [
    'Single Issue',
    'Trade Paperback',
    'Hardcover',
    'Omnibus',
    'Paperback',
    'Audiobook',
    'DVD',
    'Blu-ray',
    '4K UHD',
    'Vinyl',
    'CD',
    'Cassette',
    'SACD',
    'Board Game',
    'Expansion',
    'PS4',
    'PS5',
    'Xbox One',
    'Xbox Series',
    'Switch',
    'PC',
  ]);
  await repo.setValues('countries', [
    'US',
    'GB',
    'CA',
    'AU',
    'DE',
    'FR',
    'JP',
    'SE',
    'IS',
    'EE',
    'PL',
  ]);
  await repo.setValues('languages', [
    'en',
    'fr',
    'de',
    'ja',
    'is',
    'es',
  ]);
  await repo.setValues('age_ratings', [
    'Everyone',
    'E10+',
    'Teen',
    'T',
    'M',
    'PG',
    'PG-13',
    'R',
    'TV-MA',
    '10+',
    '12+',
    '14+',
    'Adult',
    'Mature',
  ]);
  await repo.setValues('genres', [
    'action',
    'adventure',
    'comedy',
    'crime',
    'drama',
    'fantasy',
    'horror',
    'mystery',
    'romance',
    'sci-fi',
    'thriller',
    'superhero',
    'RPG',
    'platformer',
    'roguelike',
    'cooperative',
    'strategy',
    'hip hop',
    'jazz',
    'electronic',
    'rock',
    'alternative rock',
    'trip hop',
  ]);
  await repo.setValues('story_arcs', [
    'Batman\'s Origin',
    'Gotham\'s Reckoning',
    'Replicant Hunt',
    'Xenomorph Saga',
    'Arrakis Saga',
    'War of the Ring',
    'Wild Hunt Pursuit',
    'Age of Fire',
    'Illithid Invasion',
    'Legacy Campaign',
    'The Human Condition',
    'Compton Chronicles',
  ]);
}
