import 'package:collectarr_app/features/pick_lists/pick_list_repository.dart';

Future<void> seedPickLists(PickListRepository repo) async {
  await repo.setValues('conditions', [
    'Mint',
    'Near Mint',
    'Very Fine',
    'Fine',
    'Very Good',
    'Good',
    'Fair',
    'Poor',
  ]);
  await repo.setValues('grades', [
    '10.0',
    '9.8',
    '9.6',
    '9.4',
    '9.2',
    '9.0',
    '8.5',
    '8.0',
    '7.5',
    '7.0',
    '6.5',
    '6.0',
    '5.5',
    '5.0',
  ]);
  await repo.setValues('physical_formats', [
    'Single Issue',
    'Trade Paperback',
    'Hardcover',
    'Deluxe Hardcover',
    'Omnibus',
    'Paperback',
    'Audiobook',
    'DVD',
    'Blu-ray',
    '4K UHD',
    '4K Ultra HD Blu-ray',
    'Prestige Format',
    'Vinyl',
    'CD',
    'Cassette',
    'SACD',
    'Board Game',
    'Expansion',
    'Digital',
    'PS4',
    'PS5',
    'PlayStation 5 Disc',
    'Xbox One',
    'Xbox Series',
    'Switch',
    'PC',
    'Tankobon',
  ]);
  await repo.setValues('countries', [
    'US',
    'GB',
    'CA',
    'AU',
    'DE',
    'FR',
    'JP',
    'SE',
    'IS',
    'EE',
    'PL',
    'BE',
    'KR',
  ]);
  await repo.setValues('languages', [
    'en',
    'fr',
    'de',
    'ja',
    'is',
    'es',
    'ko',
  ]);
  await repo.setValues('age_ratings', [
    'Everyone',
    'E10+',
    'Teen',
    'T',
    'M',
    'PG',
    'PG-13',
    'R',
    'TV-MA',
    '10+',
    '12+',
    '14+',
    'Adult',
    'Mature',
    '16+',
    '18+',
    'TV-14',
    'E10+ (Everyone 10+)',
    'T (Teen)',
    'T (Teen+)',
    'M (Mature 17+)',
  ]);
  await repo.setValues('genres', [
    'action',
    'action comedy',
    'action RPG',
    'action-adventure',
    'adventure',
    'alternate future',
    'alternate history',
    'alternative rock',
    'animation',
    'apocalyptic',
    'area control',
    'art rock',
    'asymmetric',
    'biography',
    'black comedy',
    'body horror',
    'campaign',
    'card game',
    'children\'s literature',
    'comedy',
    'coming-of-age',
    'conscious hip hop',
    'conspiracy',
    'cool jazz',
    'co-op multiplayer',
    'cooperative',
    'corporate',
    'corporate thriller',
    'crime',
    'crime noir',
    'crime satire',
    'CRPG',
    'drama',
    'dark ambient',
    'dark comedy',
    'dark fantasy',
    'disco',
    'downtempo',
    'dungeon crawl',
    'dungeons & dragons',
    'dystopian',
    'dystopian time travel',
    'economic',
    'electronic',
    'electronica',
    'engine building',
    'epic',
    'epic drama',
    'epic fantasy',
    'espionage',
    'experimental rock',
    'family',
    'fantasy',
    'first contact',
    'first-person shooter',
    'folk rock',
    'frame narrative',
    'funk',
    'galactic empire',
    'glam rock',
    'gothic horror',
    'greek mythology',
    'grunge',
    'hack and slash',
    'hard rock',
    'hard science fiction',
    'hard sci-fi',
    'heavy metal',
    'heist',
    'heroic fantasy',
    'high fantasy',
    'historical',
    'historical fiction',
    'history',
    'horror',
    'hunting',
    'industrial',
    'jazz rap',
    'legacy',
    'legal drama',
    'lo-fi',
    'martial arts',
    'mecha',
    'metroidvania',
    'military',
    'military sci-fi',
    'modal jazz',
    'mystery',
    'mythological',
    'mythology',
    'narrative detective',
    'nature',
    'neo-noir',
    'neo-soul',
    'network building',
    'occult detective',
    'open world',
    'opera rock',
    'philosophical',
    'philosophical fiction',
    'philosophy',
    'physics puzzle',
    'police procedural',
    'political fiction',
    'pop',
    'pop rock',
    'post-apocalyptic',
    'post-disco',
    'post-punk',
    'progressive rock',
    'proto-punk',
    'psychedelic rock',
    'psychological',
    'psychological drama',
    'psychological thriller',
    'punk rock',
    'puzzle-platformer',
    'reggae rock',
    'rock',
    'roguelite',
    'RPG',
    'satire',
    'science',
    'science fiction',
    'romance',
    'sci-fi',
    'sci-fi horror',
    'seinen',
    'shonen',
    'ska',
    'slice of life',
    'social science fiction',
    'soft rock',
    'soulslike',
    'souls-like',
    'southern gothic',
    'space exploration',
    'space opera',
    'space warfare',
    'space western',
    'sports',
    'steampunk',
    'strategy',
    'thriller',
    'superhero origin',
    'superhero',
    'supernatural',
    'suspense',
    'sword and sorcery',
    'synth-pop',
    'tactical',
    'time travel',
    'tragedy',
    'hip hop',
    'trip hop',
    'turn-based fantasy',
    'war',
    'war game',
    'western',
  ]);
  await repo.setValues('story_arcs', [
    'Batman\'s Origin',
    'Gotham\'s Reckoning',
    'Replicant Hunt',
    'Xenomorph Saga',
    'Arrakis Saga',
    'War of the Ring',
    'Wild Hunt Pursuit',
    'Age of Fire',
    'Illithid Invasion',
    'Legacy Campaign',
    'The Human Condition',
    'Compton Chronicles',
  ]);
}
