import 'package:collectarr_app/core/models/catalog_media_kind.dart';
import 'package:collectarr_app/core/api/dto/catalog/catalog_item_dto.dart';
import 'package:collectarr_app/core/api/dto/catalog/catalog_edition_dto.dart';
import 'package:collectarr_app/core/api/dto/catalog/catalog_variant_dto.dart';
import 'package:collectarr_app/core/api/dto/catalog/catalog_track_dto.dart';
import 'package:collectarr_app/core/api/dto/catalog/catalog_disc_dto.dart';
import 'package:collectarr_app/core/api/dto/catalog/catalog_series_details_dto.dart';
import 'package:collectarr_app/core/api/dto/catalog/catalog_publishing_details_dto.dart';
import 'package:collectarr_app/core/api/dto/catalog/video_catalog_details_dto.dart';
import 'package:collectarr_app/core/api/dto/catalog/music_catalog_details_dto.dart';
import 'package:collectarr_app/core/api/dto/catalog/game_catalog_details_dto.dart';
import 'package:collectarr_app/core/api/dto/catalog/boardgame_stats_details_dto.dart';

export 'package:collectarr_app/core/models/catalog_media_kind.dart';
export 'package:collectarr_app/core/api/dto/catalog/catalog_item_dto.dart';
export 'package:collectarr_app/core/api/dto/catalog/catalog_edition_dto.dart';
export 'package:collectarr_app/core/api/dto/catalog/catalog_variant_dto.dart';
export 'package:collectarr_app/core/api/dto/catalog/catalog_track_dto.dart';
export 'package:collectarr_app/core/api/dto/catalog/catalog_disc_dto.dart';
export 'package:collectarr_app/core/api/dto/catalog/catalog_series_details_dto.dart';
export 'package:collectarr_app/core/api/dto/catalog/catalog_publishing_details_dto.dart';
export 'package:collectarr_app/core/api/dto/catalog/video_catalog_details_dto.dart';
export 'package:collectarr_app/core/api/dto/catalog/music_catalog_details_dto.dart';
export 'package:collectarr_app/core/api/dto/catalog/game_catalog_details_dto.dart';
export 'package:collectarr_app/core/api/dto/catalog/boardgame_stats_details_dto.dart';

// Transitional typedefs so the rest of the codebase continues compiling.
typedef CatalogItem = CatalogItemDto;
typedef CatalogEdition = CatalogEditionDto;
typedef CatalogVariant = CatalogVariantDto;
typedef CatalogTrack = CatalogTrackDto;
typedef CatalogDisc = CatalogDiscDto;
typedef CatalogSeriesDetails = CatalogSeriesDetailsDto;
typedef CatalogPublishingDetails = CatalogPublishingDetailsDto;
typedef VideoCatalogDetails = VideoCatalogDetailsDto;
typedef MusicCatalogDetails = MusicCatalogDetailsDto;
typedef GameCatalogDetails = GameCatalogDetailsDto;
typedef BoardGameStatsDetails = BoardGameStatsDetailsDto;
typedef TrailerLink = TrailerLinkDto;

typedef ComicCatalogItem = ComicCatalogItemDto;
typedef MangaCatalogItem = MangaCatalogItemDto;
typedef BookCatalogItem = BookCatalogItemDto;
typedef MovieCatalogItem = MovieCatalogItemDto;
typedef TvCatalogItem = TvCatalogItemDto;
typedef AnimeCatalogItem = AnimeCatalogItemDto;
typedef MusicCatalogItem = MusicCatalogItemDto;
typedef GameCatalogItem = GameCatalogItemDto;
typedef BoardGameCatalogItem = BoardGameCatalogItemDto;
typedef GenericCatalogItem = GenericCatalogItemDto;
