import 'package:collectarr_app/core/models/catalog_entity_ref.dart';
import 'package:collectarr_app/core/models/catalog_item.dart';
import 'package:collectarr_app/core/models/owned_item.dart';
import 'package:collectarr_app/core/models/personal_item_anchor.dart';
import 'package:collectarr_app/core/models/tracking_entry.dart';
import 'package:collectarr_app/core/models/wishlist_item.dart';
import 'package:collectarr_app/features/collection/repositories/shelf_controller.dart';
import 'package:collectarr_app/features/library/models/library_metadata_item.dart';

CatalogItem testCatalogItem({
  String id = 'test-item-1',
  String kind = 'comic',
  String title = 'Test Item',
  String? displayTitle,
  String? synopsis,
  String? coverImageUrl,
  String? thumbnailImageUrl,
  String? coverImageData,
  String? publisher,
  String? barcode,
  String? variant,
  String? itemNumber,
  String? editionTitle,
  String? physicalFormat,
  String? physicalFormatLabel,
  String? sortKey,
  int? releaseYear,
  DateTime? releaseDate,
  List<String>? genres,
  List<String>? characters,
  List<String>? storyArcs,
  List<Map<String, dynamic>>? creators,
  List<CatalogEdition>? editions,
  CatalogSeriesDetails? series,
  VideoCatalogDetails? video,
  MusicCatalogDetails? music,
  GameCatalogDetails? game,
  CatalogPublishingDetails? publishing,
}) {
  return CatalogItem(
    id: id,
    kind: kind,
    title: title,
    displayTitle: displayTitle,
    synopsis: synopsis,
    coverImageUrl: coverImageUrl,
    thumbnailImageUrl: thumbnailImageUrl,
    coverImageData: coverImageData,
    publisher: publisher,
    barcode: barcode,
    variant: variant,
    itemNumber: itemNumber,
    editionTitle: editionTitle,
    physicalFormat: physicalFormat,
    physicalFormatLabel: physicalFormatLabel,
    sortKey: sortKey,
    releaseYear: releaseYear,
    releaseDate: releaseDate,
    genres: genres,
    characters: characters,
    storyArcs: storyArcs,
    creators: creators,
    editions: editions,
    series: series,
    video: video,
    music: music,
    game: game,
    publishing: publishing,
  );
}

CatalogEntityRef testCatalogRef(
  String id, {
  String kind = 'unknown',
  CatalogEntityType entityType = CatalogEntityType.work,
}) {
  return CatalogEntityRef(
    kind: kind,
    entityType: entityType,
    id: id,
  );
}

OwnedItem testOwnedItem({
  String id = 'owned-1',
  String itemId = 'test-item-1',
  String kind = 'comic',
  CatalogEntityRef? catalogRef,
  DateTime? createdAt,
  DateTime? updatedAt,
  bool? isDigital,
  PersonalItemAnchor? anchor,
  String? anchorType,
  String? editionId,
  String? variantId,
  String? bundleReleaseId,
  String? condition,
  String? grade,
  DateTime? purchaseDate,
  int? pricePaidCents,
  String? currency,
  String? personalNotes,
  int quantity = 1,
  int? indexNumber,
  int? coverPriceCents,
  String? rawOrSlabbed,
  String? gradingCompany,
  String? graderNotes,
  String? signedBy,
  String? labelType,
  String? customLabel,
  String? pageQuality,
  String? certificationNumber,
  bool keyComic = false,
  String? keyReason,
  String? keyCategory,
  String? keySeverity,
  int? rating,
  String? readStatus,
  DateTime? startedAt,
  DateTime? finishedAt,
  String? tags,
  DateTime? deletedAt,
  DateTime? soldAt,
  int? sellPriceCents,
  String? soldTo,
  String? ownerUserId,
  String? ownerLabel,
  String? locationId,
  String? features,
  List<String>? hdrFormats,
  String? purchaseStore,
  String? boxSetId,
  String? boxSetName,
  String? storageDevice,
  String? storageSlot,
  String? region,
  String? packaging,
  String? distributor,
  String? collectionStatus,
  DateTime? lastBagBoardDate,
  int? marketValueCents,
  String? gameCompleteness,
  bool? gameHasBox,
  bool? gameHasManual,
  String? gamePriceChartingId,
  String? gameCoreRegion,
  bool? gameValueIsLocked,
}) {
  return OwnedItem(
    id: id,
    catalogRef: catalogRef ??
        CatalogEntityRef(
          kind: kind,
          entityType: CatalogEntityType.ownedCopy,
          id: itemId,
        ),
    createdAt: createdAt,
    updatedAt: updatedAt ?? DateTime.utc(2025, 1, 1),
    isDigital: isDigital,
    anchor: anchor,
    anchorType: anchorType,
    editionId: editionId,
    variantId: variantId,
    bundleReleaseId: bundleReleaseId,
    condition: condition,
    grade: grade,
    purchaseDate: purchaseDate,
    pricePaidCents: pricePaidCents,
    currency: currency,
    personalNotes: personalNotes,
    quantity: quantity,
    indexNumber: indexNumber,
    coverPriceCents: coverPriceCents,
    rawOrSlabbed: rawOrSlabbed,
    gradingCompany: gradingCompany,
    graderNotes: graderNotes,
    signedBy: signedBy,
    labelType: labelType,
    customLabel: customLabel,
    pageQuality: pageQuality,
    certificationNumber: certificationNumber,
    keyComic: keyComic,
    keyReason: keyReason,
    keyCategory: keyCategory,
    keySeverity: keySeverity,
    rating: rating,
    readStatus: readStatus,
    startedAt: startedAt,
    finishedAt: finishedAt,
    tags: tags,
    deletedAt: deletedAt,
    soldAt: soldAt,
    sellPriceCents: sellPriceCents,
    soldTo: soldTo,
    ownerUserId: ownerUserId,
    ownerLabel: ownerLabel,
    locationId: locationId,
    features: features,
    hdrFormats: hdrFormats ?? const <String>[],
    purchaseStore: purchaseStore,
    boxSetId: boxSetId,
    boxSetName: boxSetName,
    storageDevice: storageDevice,
    storageSlot: storageSlot,
    region: region,
    packaging: packaging,
    distributor: distributor,
    collectionStatus: collectionStatus,
    lastBagBoardDate: lastBagBoardDate,
    marketValueCents: marketValueCents,
    gameCompleteness: gameCompleteness,
    gameHasBox: gameHasBox,
    gameHasManual: gameHasManual,
    gamePriceChartingId: gamePriceChartingId,
    gameCoreRegion: gameCoreRegion,
    gameValueIsLocked: gameValueIsLocked,
  );
}

ShelfEntry testShelfEntry({
  String itemId = 'test-item-1',
  String kind = 'comic',
  String title = 'Test Item',
  CatalogItem? catalogItem,
  OwnedItem? ownedItem,
  WishlistItem? wishlistItem,
  TrackingEntry? trackingEntry,
  String? locationPath,
}) {
  final resolvedCatalogItem = catalogItem ?? testCatalogItem(
    id: itemId,
    kind: kind,
    title: title,
  );
  return ShelfEntry(
    itemId: itemId,
    catalogItem: LibraryMetadataItem.fromCatalogItem(resolvedCatalogItem),
    ownedItem: ownedItem,
    wishlistItem: wishlistItem,
    trackingEntry: trackingEntry,
    locationPath: locationPath,
  );
}
